### ISSUE TITLE
useProxy not working

### ISSUE THREAD

**Issue by minhdv92** [CheshireCaat/puppeteer-with-fingerprints#1]
Hi. 
I add proxy, but its not working

plugin.useProxy('http://xxxxx:6000', {changeGeolocation : true}).useFingerprint(fingerprint);

My proxy is incomming ipv4 and outgoing ipv6

**Comment by CheshireCaat** [comment]
Good day, it seems that the problem may be on the `puppeteer` side, because it adds an `enable-feautres` argument, which can break things. Please try using `ignoreDefaultArgs` launch option like this:

```js
await plugin.launch({
  ignoreDefaultArgs: ['--enable-features=NetworkServiceInProcess2'],
});
```

If it helps, I will prepare a fix. If not, please describe your problem in more detail.

**Comment by minhdv92** [comment]
hi @CheshireCaat,
Thank for your reply.
I tried 
`await plugin.launch({
  ignoreDefaultArgs: ['--enable-features=NetworkServiceInProcess2'],
});`

But, its working with ipv4 only, I used ipv4 on incomming connection and outgoing is ipv6 then got error.
`Error: net::ERR_CONNECTION_CLOSED at https://google.com/
    at navigate (C:\workspace\fingerprint-switcher\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:240:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (C:\workspace\fingerprint-switcher\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:206:21) 
    at async CDPPage.goto (C:\workspace\fingerprint-switcher\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:439:16)
    at async C:\workspace\fingerprint-switcher\main.js:26:5
`

This is my code

`    const fingerprint = await plugin.fetch('xxxxxx', {
        tags: ['Microsoft Windows', 'Chrome'],
        dynamicPerfectCanvas : false,
        timeLimit: '15 days',
        minBrowserVersion : 96
    });
    // 25A4D1D5


    // Apply fingerprint:
    plugin.useFingerprint(fingerprint);
    plugin.useProxy('http://ipv4:6000', {changeGeolocation : true}).useFingerprint(fingerprint);
    //
    // console.log(fingerprint)
    // Launch the browser instance:
    const browser = await plugin.launch({headless : false, ignoreDefaultArgs: ['--enable-features=NetworkServiceInProcess2']});

    // The rest of the code is the same as for a standard `puppeteer` library:
    const page = await browser.newPage();
    await page.goto('https://google.com/');`

**Comment by minhdv92** [comment]
When I use ipv4 proxy, I check on iphey.com and can not bypass location error
Can you help me how to bypass this

![image](https://user-images.githubusercontent.com/77137924/222363852-e216cf89-f6a1-4235-bebc-2e074dbef64e.png)
![image](https://user-images.githubusercontent.com/77137924/222363936-fbd6d348-b4f5-4099-aa1c-acdecaa33b0c.png)
![image](https://user-images.githubusercontent.com/77137924/222363982-5e05bb0f-67b6-4ada-beb4-f85257672fe6.png)

**Comment by bablosoft** [comment]
@minhdv92, where is proxy?

**Comment by minhdv92** [comment]
@bablosoft 

proxy here

plugin.useProxy('http://ipv4:6000', {changeGeolocation : true}).useFingerprint(fingerprint);
you can try this proxy 45.144.112.150:20000

**Comment by bablosoft** [comment]
@minhdv92, I don't see any issue, except NetworkServiceInProcess2

https://i.imgur.com/G1dxl22.png

If you report about issue, please attach full code, including proxy, excluding FingerprintSwitcher keys, also actual result and expected result, video and screenshots would be nice also.

**Comment by minhdv92** [comment]
hi @CheshireCaat  @bablosoft 

I tried version 1.1.2 but still got the error

![image](https://user-images.githubusercontent.com/77137924/222433522-c09f116f-c04b-43eb-8da3-6b208dae4213.png)

**Comment by bablosoft** [comment]
@minhdv92 

DON'T attach FingerprintSwitcher keys. Next time it will be banned without refund.

Your code runs successful on my side. What are results of testing with puppeteer, BAS? Does the page will load if catch error?

Why do you think that the issue is not with proxy?

Please also attach wireshark log.

**Comment by minhdv92** [comment]
@bablosoft 
Sorry for this, I edited.
This is test results of puppteteer, 

When I run the code, its open chrome and loading page, then crash by "connection closed"

**Comment by bablosoft** [comment]
>  This is test results of puppteteer,

This is tests results for puppteteer-with-fingerprints.


Your code runs successful on my side. What are results of testing with puppeteer, BAS? Does the page will load if catch error?

Why do you think that the issue is not with proxy?

Please also attach wireshark log.

**Comment by minhdv92** [comment]
I tried with puppeteer and its working

![image](https://user-images.githubusercontent.com/77137924/222447158-0b4ee490-1478-4bed-8caa-762cc2fad90d.png)

But now, I can not create new fingerprint to test again

![image](https://user-images.githubusercontent.com/77137924/222448293-f3435f01-d346-4390-af78-8d42db6a1356.png)

**Comment by bablosoft** [comment]
Ok, we are working on ipv6 proxies problem, meanwhile you can you BAS.

**Comment by minhdv92** [comment]
thank @bablosoft 
I'm waiting your update

**Comment by bablosoft** [comment]
Fixed
