### ISSUE TITLE
Unsupported platform for browser-with-fingerprints@1.5.9

### ISSUE THREAD

**Issue by Guwudao** [CheshireCaat/puppeteer-with-fingerprints#101]
I was using Mac M2 and try to install the plugin with 

`npm i puppeteer-with-fingerprints`

but it shows Unsupported platform and logs as below:

`npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for browser-with-fingerprints@1.5.9: wanted {"os":"win32","cpu":"ia32,x64"} (current: {"os":"darwin","cpu":"arm64"})
npm ERR! notsup Valid os:   win32
npm ERR! notsup Actual os:  darwin
npm ERR! notsup Valid cpu:  ia32,x64
npm ERR! notsup Actual cpu: arm64`

so does it not support arm64 yet?

**Comment by fdciabdul** [comment]
This library only support windows
