### ISSUE TITLE
get fingerprint failed Error

### ISSUE THREAD

**Issue by fdciabdul** [CheshireCaat/puppeteer-with-fingerprints#102]
get fingerprint failed Error: Failed to get page http://54.37.75.118/prepare?id=...&data=...
i don't know why, i have premium fingerprint key 

but when deleting fingerprint key its work normally

@bablosoft @CheshireCaat

**Comment by bablosoft** [comment]
This can happen due to speed of your connection. Or if you download something in background

**Comment by fdciabdul** [comment]
> This can happen due to speed of your connection. Or if you download something in background

no c'mon i use RDP singapore server, there's no way the download speed is the issue

it happen everytime when use the fingerprint API key

but when not using apikey, it get fingerprint and launch normally

**Comment by bablosoft** [comment]
This is connection speed issues. Premium fingerprint has PerfectCanvas data, so you need to finish downloading it in reasonable time.

**Comment by fdciabdul** [comment]
@bablosoft 

![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/31664438/e3c96d6a-69ef-4c0c-8f82-ad7ba567e3d5)


![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/31664438/71a9daa7-698e-433e-bd95-9f746607b8cf)

**Comment by fdciabdul** [comment]
@bablosoft 

please take a look, i'm using contabo windows vps

https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/31664438/bf35f315-1e80-426b-a1f1-5099f5d49ed5

**Comment by bablosoft** [comment]
> @bablosoft
> 
> ![image](https://private-user-images.githubusercontent.com/31664438/331807836-e3c96d6a-69ef-4c0c-8f82-ad7ba567e3d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDI0MzcsIm5iZiI6MTcxNjA0MjEzNywicGF0aCI6Ii8zMTY2NDQzOC8zMzE4MDc4MzYtZTNjOTZkNmEtNjllZi00YzBjLThmODItYWQ3YmE1NjdlM2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE0MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMjAxYWFlZjU5NzdiZjc5OGY4YWU1ZWE0OTk1MjMwODJlY2YyYzgzNDk2YTlkMzBhYWNmNTJmNGJhZjg2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZzUMlU9bT8vc3ADCwn3vTAUc59cmvkbTiVVY9WbO8lA)
> 
> ![image](https://private-user-images.githubusercontent.com/31664438/331807844-71a9daa7-698e-433e-bd95-9f746607b8cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDI0MzcsIm5iZiI6MTcxNjA0MjEzNywicGF0aCI6Ii8zMTY2NDQzOC8zMzE4MDc4NDQtNzFhOWRhYTctNjk4ZS00MzNlLWJkOTUtOWY3NDY2MDdiOGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE0MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmODFhMmU2OThkNWRmY2JmZjllZTU5ODhmZmI2OGQ4YWYyZGQwM2Q1YjA1MDk1MDI5Zjc0NTY0N2E5ZmVjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dexaoi6dc8Kjw1aMlKtrshLPlcI_ESCXllcaiowekak)

You are missing ```:``` on first URL, on second you have correct behavior.

As I said previously, this is issue with connection speed.

Sharing your key online is strictly prohibited. Final warning, next time your key will be blocked without refund.

**Comment by bablosoft** [comment]
You can find email in your dashboard, but the issue here is with your connection speed it is not fast enough to download fingerprint with PerfectCanvas data on reasonable time.
