### ISSUE TITLE
Error: Fingerprint error: "Key is empty"     at C:\Users\pc\Desktop\puppteer\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:40:24

### ISSUE THREAD

**Issue by pythondeveloperz** [CheshireCaat/puppeteer-with-fingerprints#107]
hello i got this error i use the free version without key how can i solve this problem

**Comment by pguardiario** [comment]
I have same issue. We're interested in buying pro but I need to test it first

**Comment by bablosoft** [comment]
https://github.com/CheshireCaat/puppeteer-with-fingerprints?tab=readme-ov-file#fingerprint-usage


If you specify an empty string as the first argument, the free version will be used. For a free version you won't be able to use other tags than the default ones, as well as some other filters:

```javascript
const fingerprint = await plugin.fetch('', {
  // You can only use these tags with the free version:
  tags: ['Microsoft Windows', 'Chrome'],
  // You also cannot use such filters in the free version:
  // minBrowserVersion: 115,
});
```
