### ISSUE TITLE
Error: useProxy(), is it able to use host proxy instead of ip proxy

### ISSUE THREAD

**Issue by wengsung1997** [CheshireCaat/puppeteer-with-fingerprints#111]
const { plugin } = require('puppeteer-with-fingerprints');

const proxy = process.env.FINGERPRINT_PROXY ?? 'socks5://user-test:Test%40123@as.test.lunaproxy.net:8888';

// puppeteer usage as normal
;(async () => {
  console.log('Running tests..')

  const proxyUrl = 'socks5://user-test:Test%40123@as.test.lunaproxy.net:8888';
  const proxyServer = 'socks5://as.test.lunaproxy.net:8888';
  const proxyUser = 'user-test';
  const proxyPass = 'Test%40123';

  // const fingerprint = await plugin.fetch('', {
  //   tags: ['Microsoft Windows', 'Chrome'],
  // });

  //plugin.useFingerprint(fingerprint);
  plugin.useProxy(proxy);

  try {
    const browser = await plugin.launch({
      args: [
        '--no-sandbox',
      '--disable-dev-shm-usage',
      '--disable-blink-features=AutomationControlled',
      '--window-size=1920,1080',
      '--remote-allow-origins=*',
      '--disable-gpu',
      '--disable-backgrounding-occluded-windows',
      '--disable-background-timer-throttling',
      '--disable-crash-reporter',
      '--disable-renderer-backgrounding',
      '--disable-client-side-phishing-detection',
      `--proxy-server=${proxyUrl.split('@')[1]}`,
      ],
      proxy: {
        proxyType: 'SOCKS5',
        username: proxyUrl.split('@')[0].split('://')[1],
        password: 'Test@123',
      },
      headless: false
    });

    const page = await browser.pages();
    await page[0].authenticate({
      username: proxyUser,
      password: proxyPass
    });
    await page[0].goto('https://www.example.com/');

    console.log(`All done ✨`);

    return "200";
  } catch (error) {
    console.error('Error occurred:', error);
}
})()
    
it can launch browser successfully, but show the connection cannot be reached error page.
Log said: Error occurred: Error: net::ERR_CONNECTION_RESET at https://www.example.com/

**Comment by CheshireCaat** [comment]
Please read the documentation and the **API** description carefully.

You absolutely do not need to use the `authenticate` method, as well as specify the `proxy` setting at launch - I do not see such an option in the puppeteer **API** at all, and the plugin does not handle this configuration option. The plugin has its own and you are already using it via `useProxy`.

[Here](https://github.com/CheshireCaat/puppeteer-with-fingerprints?tab=readme-ov-file#proxy-usage) you can find examples of the proxy server format. Just use it, for example:

```js
plugin.useProxy('socks5://user-test:Test%40123@as.test.lunaproxy.net:8888');
```

Or specify a proxy in the `args` list, then you can remove the `useProxy` usage at all if you do not need additional settings.
