### ISSUE TITLE
Mobile fingerprint for passing creepjs

### ISSUE THREAD

**Issue by chun1617** [CheshireCaat/puppeteer-with-fingerprints#112]
Hello! I bought the key for mobile fingerprint, but when tried about 20 fingerprint, most of it doesn't able to get above 50 score.
Even in Android or iPhone. May I ask if there have anyway can get though the check?

**Comment by bablosoft** [comment]
creep js is well tested, make sure, you are using PerfectCanvas.

**Comment by bablosoft** [comment]
https://imgur.com/7H2e4EC - same as on real device.

**Comment by chun1617** [comment]
Queue for the PerfectCanvas take about half hour but still not yet ready. Is it possible to speed it up?
