### ISSUE TITLE
Problem with FingerPrintSwitcher

### ISSUE THREAD

**Issue by Coupdepoker** [CheshireCaat/puppeteer-with-fingerprints#114]
Hi,

Today, I bought a license of FingerprintSwitcher and was working great when i used it at the beginning.
After 2 hours, it keeps printing undefined in the shell.

const { plugin } = require('puppeteer-with-fingerprints');

const main = async () => {
  const fingerprint = await plugin.fetch('my_key');

  
  plugin.useFingerprint(fingerprint);

  const browser = await plugin.launch({
    headless : false
  });

  const page = await browser.newPage();

  await page.goto('https://whoer.net/fr');
}

main()

**Comment by Coupdepoker** [comment]
when i use the free version now, i also have the same problem

const fingerprint = await plugin.fetch('', {
    tags: ['Microsoft Windows', 'Chrome'],
  });

**Comment by CheshireCaat** [comment]
Hello, I did not understand what your problem is - attach the full code example and a screenshot of the console output or just attach the output content.

Although nothing should be output, judging by the code.

**Comment by Coupdepoker** [comment]
it's working again !! Thanks.
