### ISSUE TITLE
Can not launch

### ISSUE THREAD

**Issue by Coupdepoker** [CheshireCaat/puppeteer-with-fingerprints#115]
Hi,

Sometimes, i received this kind of fingerprint and my application can not launch and it prints:

undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
Erreur lors de l'execution de l'impression: fingerprint :  Error: Timed out while calling the "setup" method.
    at Timeout._onTimeout (C:\Users\ramia\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:34:26)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

my code:

const { plugin } = require('puppeteer-with-fingerprints');

const main = async () => {

  const fingerprint = await plugin.fetch('my_key');

  plugin.useFingerprint(fingerprint);

  const browser = await plugin.launch({
    headless : true
  });

  const page = await browser.newPage();

  await page.goto("https://ipleak.net/");
}

main()

**Comment by bablosoft** [comment]
Sharing fingerprints is prohibited. If you continue do that, your key will be blocked.

**Comment by Coupdepoker** [comment]
Sorry , i forgot

**Comment by Coupdepoker** [comment]
after rebooting my computer, i dont get the error. Maybe it was a problem of internet connection
