### ISSUE TITLE
CanvasInspector request with 1MB+ size always fails to fetch FP

### ISSUE THREAD

**Issue by dr3adx** [CheshireCaat/puppeteer-with-fingerprints#116]
Steps to reproduce:

1) Open CanvasInspector, navigate to d1sc0rd.com/register and solve captcha
2) Save all 62 canvasinspector requests to file (notice the file size is over 1 MB, and yes all calls are used for fingerprinting)

3) Fetch fingerprint with this perfect request

Output forever stuck at obtaining fingerprint:
`(PerfectCanvas) Start obtaining fingerprint
`
Expected output:
`
(PerfectCanvas) Start obtaining fingerprint
(PerfectCanvas) Request id is 1pi4vwp1kng
`

**Comment by bablosoft** [comment]
For discord, use native canvas.

**Comment by dr3adx** [comment]
> For discord, use native canvas.

What about other settings, like safeElementSize, safeBattery, emulateDeviceScaleFactor? Should those be on or off for discord?
