### ISSUE TITLE
Uncaught Error: Failed to get page http://ip.bablosoft.com/?requestid=53341 with HttpClient

### ISSUE THREAD

**Issue by SCParrot** [CheshireCaat/puppeteer-with-fingerprints#118]
it work fine for a long time util today i got error `Uncaught Error: Failed to get page http://ip.bablosoft.com/?requestid=53341 with HttpClient`
![1](https://github.com/user-attachments/assets/109f5079-afaa-4682-bef0-f2aadfda2d40)

**Comment by CheshireCaat** [comment]
Greetings, apparently you have local problems accessing the default IP information service - maybe your provider started blocking it or something like that.

In any case, there is a workaround - you can use the **ip-api** service by specifying the appropriate [settings](https://github.com/CheshireCaat/browser-with-fingerprints/blob/512df9ddc5880a8fe90a5de6e7d21bff30d4a160/src/index.d.ts#L174) when installing the proxy.

**Comment by SCParrot** [comment]
thanks! I found it's because my proxy is blocked.
