### ISSUE TITLE
Failed to get proxy ip

### ISSUE THREAD

**Issue by soya-miruku** [CheshireCaat/puppeteer-with-fingerprints#12]
```
const proxy = await pchain.anonymizeProxy(process.env.PROXY_URL as string);
plugin
.useProxy(proxy, {
	// changeBrowserLanguage: true,
	changeGeolocation: true,
	changeTimezone: true,
	changeWebRTC: true,
})
.useFingerprint(fingerprint);
```
i am not sure why is this happening, i have tried simple proxies too, but it just keeps returning failed to get proxy ip and crashes... any help?

**Comment by bablosoft** [comment]
This error means that proxy doesn't work, if you believe that it is valid and checked it with curl, please send it to mail.to.twaego@gmail.com.

> and crashes

What exactly crashes? Node instance? Browser? If browser crashes, this is a major issue, can you attach full source with all data, so we can reproduce it?

**Comment by soya-miruku** [comment]
@bablosoft update for everyone else too, you were right, it was the proxies fault, they had banned ip.bablosoft.com which i believe is used to retrieve the ip, unblocking this fixed the issue.
