### ISSUE TITLE
not working after new update : FingerprintSwitcher key is missing / invalid format error

### ISSUE THREAD

**Issue by singhaditya4** [CheshireCaat/puppeteer-with-fingerprints#120]
```
node_modules\browser-with-fingerprints\src\plugin\connector\index.js:40
      if (error) throw new Error(error);
                       ^

Error: Incorrect format
    at .\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:40:24

Node.js v20.17.0
```
When trying to fetch 

and
```
node_modules\browser-with-fingerprints\src\plugin\connector\index.js:40
      if (error) throw new Error(error);
                       ^

Error: FingerprintSwitcher key is missing
    at .\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:40:24

Node.js v20.17.0
```
when using JSON file

**Comment by singhaditya4** [comment]
was on node 18.16 then updated to 20.17 LTS, previous plugin works but after chrome 127 update (npm update) new engine doesn't work

**Comment by CheshireCaat** [comment]
Greetings!

According to the last engine update now it's necessary to specify the service key for the launch and spawn methods Check out [this](https://github.com/CheshireCaat/puppeteer-with-fingerprints?tab=readme-ov-file#fingerprint-usage) section:

> Warning: according to the latest engine and service updates, now it's also necessary to specify the service key for applying the fingerprint. The key must match the one with which the fingerprint was obtained - it can only be omitted if the free version was used (an empty string for the key):

Example:

```js
const { plugin } = require('puppeteer-with-fingerprints');

const fingerprint = await plugin.fetch('SERVICE_KEY', {
  tags: ['Microsoft Windows', 'Chrome'],
});
plugin.useFingerprint(fingerprint);

await plugin.launch({ key: 'SERVICE_KEY' });
```

If you use a fingerprint from a file, you still need to use the key.

**Comment by CheshireCaat** [comment]
@singhaditya4 why are you writing about this here, write to the email related to the service and payments, I am not connected with this and can not help in any way.

**Comment by singhaditya4** [comment]
> @singhaditya4 why are you writing about this here, write to the email related to the service and payments, I am not connected with this and can not help in any way.

I did but this doesn't help dude i am stuck here and the payment gateway is so sketchy . I can't launch the browser and locked out for doing anything.

**Comment by CheshireCaat** [comment]
Have you written about your problem to this email?

![image](https://github.com/user-attachments/assets/c65ffd46-27fb-45a2-8e9e-27dac4a41faa)

**Comment by CheshireCaat** [comment]
> I can't launch the browser and locked out for doing anything.

You can use the plugin without the premium version.

**Comment by singhaditya4** [comment]
> > I can't launch the browser and locked out for doing anything.
> 
> You can use the plugin without the premium version.

![image](https://github.com/user-attachments/assets/0c9cac98-bd57-4bbf-8d33-83f27aa1f65a)
doesn't work

**Comment by CheshireCaat** [comment]
Fetch free fingerprints and use them until the problem with the key is solved.

**Comment by dr3adx** [comment]
> Fetch free fingerprints and use them until the problem with the key is solved.

why are we now required to have **active** key to use fingerprints we fetched **way before**?
it should be possible to use already saved fingerprints without active premium, its feels very money grabby right now

**Comment by singhaditya4** [comment]
> @singhaditya4 @dr3adx you can read additional info [here](https://community.bablosoft.com/topic/29016/error-fingerprintswitcher-key-is-missing).
> 
> My opinion is that the new approach is correct, it would just be better to add it earlier.
> 
> I do not know of any service that would allow you to use the functionality of the paid version without the paid version itself. Fingerprints have become part of the license, which is quite logical, if you have difficulties with keys, you can use the free version.
> 
> These changes are not my decision. In any case, for my part, I also can't change this in any way, just try to help with solving problems with the plugin, not with the service.
> 
> I think that further discussions here are pointless.

I agree from the business perspective its right and essential.
but lol your payment gateway is causing problems to me so i had to roll back to the older version for now

**Comment by TheGP** [comment]
You are not a business but a circus, there for it should remain free.

**Comment by Mohsentrade741** [comment]
Hi
Although in the manual it says use an empty string for fre version as key, but it shows this error when fetching a fingerprint: "Key is empty"
I'm testing to see if I can use the service to completely bypass the web site that I need or not, and it was working till couple of days ago.
Any idea?
