### ISSUE TITLE
Not supported on macos or linux

### ISSUE THREAD

**Issue by urasdbwd** [CheshireCaat/puppeteer-with-fingerprints#122]

**Comment by CheshireCaat** [comment]
Hello, please check:

https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/101
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/76
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/70
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/50
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/36
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/28
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/27
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/5
