### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by yuhaya** [CheshireCaat/puppeteer-with-fingerprints#123]
Cannot connect to the WebSocket server (reason: undefined) This could be due to the fact that the engine was not downloaded or unpacked correctly. Try completely deleting the engine folder and restarting the code until it completes. If this does not help, open an issue with a detailed description of the problem

Delete and re-download according to the prompts, but the problem still exists and it cannot be started normally
I have tried various methods, but none of them worked.

How to request a refund？

**Comment by CheshireCaat** [comment]
Greetings.

Please attach the test code so that the problem can be repeated.

**Comment by CheshireCaat** [comment]
Another thing you can try to do is download the engine manually from this link:

http://downloads.bablosoft.com/distr/FastExecuteScriptProtected64/27.8.1/FastExecuteScriptProtected.x64.zip

After downloading, the archive must be placed in the folder with the engine, for example:

`your_project_folder/data/engine/27.8.1/FastExecuteScriptProtected.x64.zip`

**Comment by yuhaya** [comment]
> Another thing you can try to do is download the engine manually from this link:
> 
> https://downloads.bablosoft.com/distr/FastExecuteScriptProtected64/27.8.1/FastExecuteScriptProtected.x64.zip
> 
> After downloading, the archive must be placed in the folder with the engine, for example:
> 
> `your_project_folder/data/engine/27.8.1/FastExecuteScriptProtected.x64.zip`

```
console.log("get cache_xfinger start");
            plugin.setServiceKey('xxxxxxxxxxx');
            var cache_xfinger = await plugin.fetch({
                tags: ['Desktop', 'Chrome']
            });
            console.log("get cache_xfinger end");

            plugin.useFingerprint(cache_xfinger);

            console.log(cache_xfinger);
            var as = await plugin.launch();
            console.log("puppeteer launch succ");
            var pid = as.process().pid;
            console.log(pid);
```
FastExecuteScriptProtected.x64.zip was downloaded normally. I manually compared the md5 value and there was no problem.

Either the startup failed or the fingerprint could not be obtained for a long time. It has been 9 hours since I purchased the key, and the problem has not been solved.

I found that your Engine has 800M, which is too large for us and is not suitable for our application scenario.

Can you provide a refund channel? Thank you
output:

> get cache_xfinger start
> The browser is installing - this may take some time.

FastExecuteScriptProtected.x64.zip was downloaded normally. I manually compared the md5 value and there was no problem.

Either the startup failed or the fingerprint could not be obtained for a long time. It has been 9 hours since I purchased the key, and the problem has not been solved.

I found that your Engine has 800M, which is too large for us and is not suitable for our application scenario.

Can you provide a refund channel? Thank you

**Comment by CheshireCaat** [comment]
mail.to.twaego@gmail.com

**Comment by yuhaya** [comment]
> [mail.to.twaego@gmail.com](mailto:mail.to.twaego@gmail.com)

The product is completely unusable, why don't you support refunds?

**Comment by CheshireCaat** [comment]
Please write your refund request to attached mail

**Comment by yuhaya** [comment]
> Please write your refund request to attached mail

I sent it, and you replied that you couldn't reproduce the problem, so you refused to refund. Is this a complete scam?

**Comment by CheshireCaat** [comment]
I have not answered you anywhere except for this ticket, I am not directly connected with payments and the service.
