### ISSUE TITLE
垃圾

### ISSUE THREAD

**Issue by yuhaya** [CheshireCaat/puppeteer-with-fingerprints#125]
完全不能用，付款后不退款

**Comment by CheshireCaat** [comment]
Are you kidding me?

I have already said that the plugin and I are not directly related to the service and payments.

And you are not interested in solving the problem, saying from the very beginning that you only need a refund.


You could try out the plugin on the free version, you could help deal with YOUR local problem, but you don't need it.

I will ignore and close your next tickets and messages.

Also I will not provide you with any support as a developer at all.
