### ISSUE TITLE
How to let user free resize resolution

### ISSUE THREAD

**Issue by hailongtrinh** [CheshireCaat/puppeteer-with-fingerprints#13]
is there a way to let the user can freely drag to change the browser resolution with the mouse ?
currently resolution is set following to fingerprint, i don't see any option that allows user to freely drag to change browser resolution or even use maximum button.
Thanks

**Comment by bablosoft** [comment]
This is done on purpose, in order to make browser resolution the same as on target machine where it was collected.

**Comment by hailongtrinh** [comment]
Is there any solution for this, I really need this :(((
