### ISSUE TITLE
[Bug]:  https://bablosoft.com/scripts/FingerprintPluginV8/properties 

### ISSUE THREAD

**Issue by TheGP** [CheshireCaat/puppeteer-with-fingerprints#134]
[bablosoft-server] SyntaxError: Unexpected token '<', "<html>
[bablosoft-server] <h"... is not valid JSON
[bablosoft-server] at JSON.parse (<anonymous>)
[bablosoft-server] at IncomingMessage.<anonymous> (\node_modules\bas-remote-node\src\services\utils.js:17:20)

**Comment by TheGP** [comment]
1.5.0

**Comment by CheshireCaat** [comment]
There are problems on the server side - you need to upgrade plugin to a new version, or wait for a solution during the day.

**Comment by OnlineTrackerWhatsApp** [comment]
sorry for that

**Comment by CheshireCaat** [comment]
@holanati please create separate ticket with detailed info.
