### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by OnlineTrackerWhatsApp** [CheshireCaat/puppeteer-with-fingerprints#135]
**Describe the bug**
Installed 2.0.2 version but still not able to generate fingerprint. 
its not throwing any error

here my code with new update, please help me if I did any wrong.

**Code example**
plugin.setServiceKey('MYKEY');
console.log("before fatch coming");
let fingerprint = await plugin.fetch({
    tags: browser,
    minBrowserVersion: 110,
    maxBrowserVersion: 118,
    timeLimit: '65 days',
});
console.log("after fetch not coming");
let Data = JSON.parse(fingerprint)

**Expected behavior**
when I run code its just print 1st log which is "before fatch coming" then program is terminated. 

**Screenshots**
![image](https://github.com/user-attachments/assets/8e0c7ea8-23b4-4017-8d51-98029feaa5b6)

**System (please complete the following information):**
 - Plugin version [e.g. 2.0.2]
 - Node version [e.g. 20.12.2]

**Comment by CheshireCaat** [comment]
Hello, have you found the cause of the problem?

**Comment by CheshireCaat** [comment]
Please attach the full code - along with the imports and so on.

**Comment by CheshireCaat** [comment]
I can't reproduce the problem, try deleting the `data/script` folder and rerunning the code.

**Comment by OnlineTrackerWhatsApp** [comment]
i trying to delete the data/script folder and rerunning the code but not
resolve the issue.

**Comment by CheshireCaat** [comment]
Please try to update the **NodeJS** version - I checked your code on **20.17.0** and it works fine for me.

Can you also specify your **OS** version and architecture?

**Comment by OnlineTrackerWhatsApp** [comment]
[image: image.png]

64-bit operating system, x64-based processor
 *NodeJS also updated but it's not working.*

**Comment by CheshireCaat** [comment]
Please check that there is the `FastExecuteScript.exe` file inside the `data/script/27.9.2` folder.

Also, if you have an antivirus or firewall enabled, it can delete or block the executable file, so check this point too.

**Comment by OnlineTrackerWhatsApp** [comment]
I checked all thing but it's not working please help

**Comment by CheshireCaat** [comment]
Please install the **2.0.3** version and show me console output.

**Comment by OnlineTrackerWhatsApp** [comment]
[image: image.png] not working

**Comment by CheshireCaat** [comment]
Your images not loaded, currently I have not any other options for you, try to debug and find out the reason on your side.

**Comment by OnlineTrackerWhatsApp** [comment]
[image: image.png]

**Comment by OnlineTrackerWhatsApp** [comment]
hi, using the Windows 2012 RDP server to get an error please guide how to
fix it.

[image: image.png]

**Comment by CheshireCaat** [comment]
The browser engine versions, like the original **Chromium**, will not work on versions of **Windows** earlier than **10**. The server version you specified is based on the regular **8**.

Also, please use **GitHub** when attaching images, and do not send by mail, because your screenshots are not displayed correctly.
