### ISSUE TITLE
Unable to open upload file dialog

### ISSUE THREAD

**Issue by ClassAxion** [CheshireCaat/puppeteer-with-fingerprints#14]
I'm unable to open upload file dialog manually, when I click on any button that should open upload file dialog nothing happens. I tried on multiple websites. I also tried to trigger the upload buttons with JS using `document.querySelector('...').click()` with no luck.

**Comment by CheshireCaat** [comment]
If you need to manually upload a file without processing it through the libraries, you should use [this](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setInterceptFileChooserDialog) CDP method and specify `false` for the `enabled` option.

The custom browser, unlike the usual one, by default turns on the interception of the file dialog.
