### ISSUE TITLE
Playback of protected content is not enabled 

### ISSUE THREAD

**Issue by MarioCodarin** [CheshireCaat/puppeteer-with-fingerprints#18]
Hello,
how can I activate the playback? Maybe it's a Widevine problem or old version.
Did someone get the same problem?

**Comment by CheshireCaat** [comment]
Next time you can just close the ticket without changing the title and message.

**Comment by bablosoft** [comment]
We need to support Widevine(without VMP), safe browsing and browser components, just like BAS does.

**Comment by bablosoft** [comment]
@MarioCodarin I've restore your topic, please don't delete it.

**Comment by bablosoft** [comment]
Widevine should be enabled for now, but Verified Media Path is not supported
