### ISSUE TITLE
How to use it with plugins? 

### ISSUE THREAD

**Issue by marcusdiy** [CheshireCaat/puppeteer-with-fingerprints#21]
Hi, my project requires to use puppeteer-extra-plugin-recaptcha
but if i do plugin.use(RecaptchaPlugin(... it doesnt work as its not even a function
Is it even puppeteer or not? How to get access to the underline puppeteer instance?
Thanks

**Comment by marcusdiy** [comment]
I've tried like this, puppeteer works, but the fingerprint is not applied.

```
    const puppeteer = require('puppeteer-extra');
    const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');
    puppeteer.use(RecaptchaPlugin({
      provider:  { id: "2captcha", token: "XXXXXXXXXX" }, visualFeedback: true,
      solveInViewportOnly: true, solveInactiveChallenges: true
    }));

    const { createPlugin } = require('puppeteer-with-fingerprints');
    const plugin = createPlugin({ launch: (options) => puppeteer.launch(options) });
    const browser = await plugin.launch({headless: false});

    page = await browser.newPage();
    await page.goto('https://pixelscan.net ');
    //await page.solveRecaptchas(); <-- now exists
    while (true) await Utils.sleep(50);
```

**Comment by CheshireCaat** [comment]
The documentation has a [description](https://github.com/CheshireCaat/puppeteer-with-fingerprints#more-info) of the method for creating a separate plugin instance. Working with `puppeteer-extra` has not been tested and may lead to bugs or fingerprint inconsistencies, but if you really need it, you can use it:

```js
const puppeteer = require('puppeteer-extra');
const { createPlugin } = require('puppeteer-with-fingerprints');

const plugin = createPlugin(puppeteer);
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');
/// your code
```

If I answered your question, please close the ticket.

**Comment by marcusdiy** [comment]
Well, yeah. Is there any other way you would recommend for solving captchas?
My code is essentially the same as yours... recaptcha plugin is getting loaded.
The problem is with the fingerprint plugin wich is not getting applied.

```
const puppeteer = require('puppeteer-extra');
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');
const { createPlugin } = require('puppeteer-with-fingerprints');

puppeteer.use(RecaptchaPlugin({ provider: { id: "2captcha", token: "xxxxxxxxx" } }));

const plugin = createPlugin({ launch: (options) => puppeteer.launch(options) });
await plugin.fetch('XXXXXXXXXXX', { tags: ['Apple Mac', 'Edge'] });
const browser = await plugin.launch({ headless: false });

page = await browser.newPage();
await page.goto('https://pixelscan.net');
// await page.solveRecaptchas(); <-- at least the method now is loaded
while (true) await Utils.sleep(50); // prevent from closing

```

**Comment by marcusdiy** [comment]
const puppeteer = require('puppeteer-extra');
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');
const { createPlugin } = require('puppeteer-with-fingerprints');

puppeteer.use(RecaptchaPlugin({ provider: { id: "2captcha", token: "xxxxxxxxx" } }));

const plugin = createPlugin({ launch: (options) => puppeteer.launch(options) });
let fingerprint = await plugin.fetch('XXXXXXXXXXX', { tags: ['Android'] });
plugin.useFingerprint(fingerprint);
const browser = await plugin.launch({ headless: false });

page = await browser.newPage();
await page.goto('https://pixelscan.net');
// await page.solveRecaptchas(); <-- at least the method now is loaded
while (true) await Utils.sleep(50); // prevent from closing
