### ISSUE TITLE
How to set userAgent of a page ?

### ISSUE THREAD

**Issue by EliteDev2** [CheshireCaat/puppeteer-with-fingerprints#24]
I want to set mobile useragent to a specific page , so far 
`await searchPage.setUserAgent(userAgent);`
and 
`searchpage.emulate(device)` doesn't seem to work . How can i do this ?

**Comment by bablosoft** [comment]
Changing only user agent is very dangerous and can be detected. You need to change fingerprint instead, it changes lots of properties including user agent.

**Comment by EliteDev2** [comment]
I'm actually okay if website detect any abnormaly by doing this , I want to set or emulate mobile useraAgent to a specific page for some seconds and then continue with the Default userAgent defined in my fingerprint for further tasks.
Both `setUseragent` and `page.emulate()` Doesn't seem to work.

Is there any way to archive this ? changing the fingerprint to mobile and launching another instance will not be suitable for my tasks.

**Comment by bablosoft** [comment]
Setting user agent through CDP will be overridden with fingerprint data. So it has no effect.

Right now it is not possible to change fingerprint or any of its part at runtime. Maybe we will add this possibility in the future.

You can try to examine source and change fingerprint files. But it won't necessarily work. And it is a hack, so no docs on it.
