### ISSUE TITLE
parallel launch browsers

### ISSUE THREAD

**Issue by dmitry200** [CheshireCaat/puppeteer-with-fingerprints#25]
When trying to launch multiple instances (i use c# script which runs js in several threads)

Error: Lock is not acquired/owned by you
    at C:\Users\username\Desktop\project\bin\Debug\node_modules\proper-lockfile\lib\lockfile.js:285:43
    at LOOP (node:fs:2673:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ENOTACQUIRED'
}

I bought a full license, and I dont understand what the error is

**Comment by bablosoft** [comment]
This error means that you are trying to run several applications from same folder.

If you are not trying to do so, please reopen the ticket and attach all necessary information to reproduce the problem: source code and detailed description.

Avoid to place your key here.

Note that C# is not supported, so source must be written with node.js.

**Comment by dmitry200** [comment]
try
          {

            const fingerprint = await plugin.fetch('MYKEY', {
                tags: ['Microsoft Windows', 'Chrome'],
                minBrowserVersion: 112,
                minWidth: 1312,
                minHeight: 768,
                maxWidth: 1920,
                maxHeight: 1080,
                usePerfectCanvas: true
            });

            plugin.useFingerprint(fingerprint);

              plugin.useProxy(`${process.argv[3]}:${process.argv[4]}:${process.argv[5]}:${process.argv[6]}`, {
                changeTimezone: true,
                changeGeolocation: true,
                changeBrowserLanguage: false,
              });


                var browser = await plugin.launch({ 

                    headless: false,
                    userDataDir: `C:\\Users\\username\\Desktop\\dir\\${process.argv[2]}`,
                    executablePath: `C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe`,
                    args: [
                            `--no-sandbox`,
                            `--disable-dev-shm-usage`, //https://github.com/puppeteer/puppeteer/issues/1321#issuecomment-378361236
                            `--disable-gpu`,
                    ],
                });
                  console.log(browser.wsEndpoint());

          } catch(e) {
              console.log(e);
          }

          await sleep(999999);


I run this script from my c# and there I already connect to the browser, I dont understand what you mean by "This error means that you are trying to run several applications from the same folder."

what is the best way to solve this?

**Comment by dmitry200** [comment]
make 10 folders and run a copy from them in each thread? its stupid

**Comment by dmitry200** [comment]
> This error means that you are trying to run several applications from same folder.
> 
> If you are not trying to do so, please reopen the ticket and attach all necessary information to reproduce the problem: source code and detailed description.
> 
> Avoid to place your key here.
> 
> Note that C# is not supported, so source must be written with node.js.

why did I buy a license then?

**Comment by bablosoft** [comment]
> I run this script from my c# and there I already connect to the browser

The script that you have provided is single threaded, it runs without any issue, except `sleep` is not defined.

I've modified it to run with multiple threads, several browsers start sequentially and then can be controlled in parallel.

```javascript
const puppeteer = require('puppeteer-core');
const { plugin } = require('puppeteer-with-fingerprints');

async function Main(index)
{
    try
      {

        const fingerprint = await plugin.fetch('KEY', {
            tags: ['Microsoft Windows', 'Chrome'],
            minBrowserVersion: 112,
            minWidth: 1312,
            minHeight: 768,
            maxWidth: 1920,
            maxHeight: 1080,
            usePerfectCanvas: true
        });

        plugin.useFingerprint(fingerprint);

          plugin.useProxy(`PROXY`, {
            changeTimezone: true,
            changeGeolocation: true,
            changeBrowserLanguage: false,
          });


            var browser = await plugin.launch({ 
                headless: false,
                userDataDir: `PROFILEPATH/${index}`,
                args: [
                ],
            });
              console.log(browser.wsEndpoint());

      } catch(e) {
          console.log(e);
      }

      await new Promise(r => setTimeout(r, 100000000));
}

 Main(1)
 Main(2)
 Main(3)

```

> make 10 folders and run a copy from them in each thread? its stupid

Multithreading is supported, check example above or https://github.com/CheshireCaat/puppeteer-with-fingerprints/blob/master/examples/parallel.js for more details.

> why did I buy a license then?

Differences between free and premium can be seen here:

https://fingerprints.bablosoft.com/#pricing

**Comment by dmitry200** [comment]
how is your script different from mine? I also pass different strings to argv and as a result I get different userdir

userDataDir: `C:\\Users\\username\\Desktop\\dir\\${process.argv[2]}`,
userDataDir: `PROFILEPATH/${index}`,

these are different lines in any case

**Comment by bablosoft** [comment]
> I also pass different strings to argv and as a result I get different userdir

If you are running multiple app instances from same folder, 'Lock is not acquired/owned by you' is expected error.

Use multithreading
