### ISSUE TITLE
timeout when fetching with perfectCanvasRequest

### ISSUE THREAD

**Issue by mannok** [CheshireCaat/puppeteer-with-fingerprints#32]
Am I fetching correctly?

![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/458220/c8ace505-651b-4802-aa89-350831b3076a)

![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/458220/19d56a52-8528-4471-9db7-eee8f445e244)

**Comment by bablosoft** [comment]
@CheshireCaat can you check this, timeout handling must be identical to BAS if PerfectCanvas request is specified

**Comment by CheshireCaat** [comment]
@mannok The default timeout for methods like **fetch** is set to 5 minutes (300000 milliseconds). If this is causing problems, you can change it by setting an environment variable:

```js
process.env.FINGERPRINT_TIMEOUT = 600000; // 10 minutes and so on.
```

**Comment by mannok** [comment]
@CheshireCaat for the workaround

**Comment by mannok** [comment]
@CheshireCaat for the workaround
