### ISSUE TITLE
fingerprint fetching with perfectCanvasRequest is way to slow

### ISSUE THREAD

**Issue by mannok** [CheshireCaat/puppeteer-with-fingerprints#33]
some statistic fyr...

code:
```
(async (): Promise<void> => {
  process.env.FINGERPRINT_TIMEOUT = '1200000';

  console.log('start time', new Date().toLocaleTimeString());

  const result = await Promise.all([...Array(8)].map((_, i) => new Promise(async (resolve, reject) => {
    try {
      // Get a fingerprint from the server:
      const fingerprint = await plugin.fetch('', {
        tags: ['Desktop', 'Chrome'],
        minBrowserVersion: 115,
        maxBrowserVersion: 115,
        perfectCanvasRequest: fs.readFileSync(path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '../configs/perfect-canvas-request.config'), { encoding: 'utf8' })
      });

      console.log(i, new Date().toLocaleTimeString());

      resolve(fingerprint);
    }
    catch (ex) {
      reject(ex);
    }
  })));
})();
```

Initially I would like to fetch the fingerprints in parallel, but obiviously that's not how it works... It takes >5 mins to get the first fingerprint, another 5 mins to get the second one, 1 more min to get the 3rd one and eventually an exception was thrown after 10 more mins...   Is there any advice?

![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/458220/b916e2cf-f128-41b8-a848-ee7f40a2d1b2)

**Comment by bablosoft** [comment]
Please never share your key.

You can read more here.

https://wiki.bablosoft.com/doku.php?id=perfectcanvas#limitations

**Comment by bablosoft** [comment]
I've just tried to get fingerprint with PerfectCanvas request for creepjs and got it in 1 minute approximatelly.
