### ISSUE TITLE
does this project bypasses CloudFlare?

### ISSUE THREAD

**Issue by luluhoc** [CheshireCaat/puppeteer-with-fingerprints#34]
does this project bypasses CloudFlare? 

for example nowsecure.nl?

**Comment by bablosoft** [comment]
I've checked it out, it works with BAS.

For `puppeteer-with-fingerprints` it doesn't work. We will check it out soon.

**Comment by luluhoc** [comment]
> I've checked it out, it works with BAS.
> 
> 
> 
> For `puppeteer-with-fingerprints` it doesn't work. We will check it out soon.

Thanks keep me posted apparently cloudflare is now somehow detecting when puppeteer is connected to devtools.

Lmk if you'll have any insight.

**Comment by bablosoft** [comment]
Hi again

We have figured out what the issue was. It was related to finding browser setting related to external ip: timezone, language, locale something from that list. It was reproduced only on my PC and for my ip. On our other team member PC it never reproduces, it also doesn't reproduces with proxy.

While we will continue to investigate, maybe updating ip database will help,

Feel free to use `puppeteer-with-fingerprints` with Cloudflare, it must work on your side.

**Comment by luluhoc** [comment]
@bablosoft so you mean that the ip location must match the settings from given country right?

**Comment by bablosoft** [comment]
Yes, but that is done automatically by library

**Comment by NCLnclNCL** [comment]
> Hi again
> 
> We have figured out what the issue was. It was related to finding browser setting related to external ip: timezone, language, locale something from that list. It was reproduced only on my PC and for my ip. On our other team member PC it never reproduces, it also doesn't reproduces with proxy.
> 
> While we will continue to investigate, maybe updating ip database will help,
> 
> Feel free to use `puppeteer-with-fingerprints` with Cloudflare, it must work on your side.

I think clouflare detect devtool runtime, because if i kill chromedriver it will can pass cloudflare

**Comment by bablosoft** [comment]
> I think clouflare detect devtool runtime, because if i kill chromedriver it will can pass cloudflare

There are sites which detects `Runtime.enable` call, but we protect against it.

Cloudflare could detect some widely used Chromium flags.

[NCLnclNCL](https://github.com/NCLnclNCL) Cloudflare is well tested at least for BAS. Can you provide source which demonstrates the issue.

I don't have any issues right now. https://i.imgur.com/DsCpEro.gif

**Comment by luluhoc** [comment]
> > I think clouflare detect devtool runtime, because if i kill chromedriver it will can pass cloudflare
> 
> 
> 
> There are sites which detects `Runtime.enable` call, but we protect against it.
> 
> 
> 
> Cloudflare could detect some widely used Chromium flags.
> 
> 
> 
> [NCLnclNCL](https://github.com/NCLnclNCL) Cloudflare is well tested at least for BAS. Can you provide source which demonstrates the issue.
> 
> 
> 
> I don't have any issues right now. https://i.imgur.com/DsCpEro.gif

Can you give me the link to the code that protects against it?

**Comment by bablosoft** [comment]
> Can you give me the link to the code that protects against it?

It is Chromium patches, we don't disclosure them.

**Comment by bablosoft** [comment]
> We have figured out what the issue was. It was related to finding browser setting related to external ip: timezone, language, locale something from that list. It was reproduced only on my PC and for my ip. On our other team member PC it never reproduces, it also doesn't reproduces with proxy.

We have found the issue here. If you take orignal Chrome and change browser language to Ukrainian, you will have infinite page reload

https://i.imgur.com/qAmjd7q.png

And it happens not 100% of time. Because BAS/puppeteer-with-fingerprints behaves same as original browser, tht is not an issue.

**Comment by luluhoc** [comment]
> > We have figured out what the issue was. It was related to finding browser setting related to external ip: timezone, language, locale something from that list. It was reproduced only on my PC and for my ip. On our other team member PC it never reproduces, it also doesn't reproduces with proxy.
> 
> 
> 
> We have found the issue here. If you take orignal Chrome and change browser language to Ukrainian, you will have infinite page reload
> 
> 
> 
> https://i.imgur.com/qAmjd7q.png
> 
> 
> 
> And it happens not 100% of time. Because BAS/puppeteer-with-fingerprints behaves same as original browser, tht is not an issue.

@bablosoft so you mean if you tamper with language of the browser you get infinite loading.

**Comment by bablosoft** [comment]
> so you mean if you tamper with language of the browser you get infinite loading.

If you set Ukrainian language as interface language for real Chrome - nowsecure.nl won't be loaded(well with some probability).

I've tried about 10 times with German language and got 0 infinite loads. https://i.imgur.com/BkhMerz.png

In other words, that is problem specific just for one language and reproduces on real browser. 

--------------------

So you can ignore this comment https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/34#issuecomment-1655489340 , products that we provide works just like a real browser for nowsecure.nl, sorry that got you confused.
