### ISSUE TITLE
Issues while trying to run it on docker

### ISSUE THREAD

**Issue by mir3u** [CheshireCaat/puppeteer-with-fingerprints#35]
Hi, I am trying to run this application on an windows nano server docker, but I get this error
![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/48906369/d34cef3e-2ef2-4943-b666-64905d5565b7)
Does this library supports running on a windows server or only on on-premise devices? Is there any considerations when running it on a docker image?

Update:

I changed to a different windows image but I now have a different error
![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/48906369/44c418c4-c1b1-4002-8dc8-fad63757bdc3)

**Comment by bablosoft** [comment]
Hi, it is tested on local Windows and Windows server and these platforms are officially supported. Haven't tested on docker.

Have you tried to run this type of image?

> `Windows` is the largest image and has full Windows API support for workloads.

https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images

**Comment by mir3u** [comment]
It worker with the windows container. Thanks!
