### ISSUE TITLE
Doesn't work on mac m1

### ISSUE THREAD

**Issue by luluhoc** [CheshireCaat/puppeteer-with-fingerprints#36]
```
error browser-with-fingerprints@1.4.2: The platform "darwin" is incompatible with this module.
error browser-with-fingerprints@1.4.2: The CPU architecture "arm64" is incompatible with this module.
```

After trying to install

**Comment by luluhoc** [comment]
> Only Windows is supported

@bablosoft any plans for linux and mac?

**Comment by CheshireCaat** [comment]
@luluhoc please, check documentation and closed issues:

- https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/29
- https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/28
- https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/27
- https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/23
- https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/5

**Comment by luluhoc** [comment]
> @luluhoc please, check documentation and closed issues:
> 
> 
> 
> - https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/29
> 
> - https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/28
> 
> - https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/27
> 
> - https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/23
> 
> - https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/5

Yeah, I get it but there is no Linux plans? Many people are scraping on Linux
