### ISSUE TITLE
Failed to get Proxy

### ISSUE THREAD

**Issue by EliteDev2** [CheshireCaat/puppeteer-with-fingerprints#37]
Getting the following error after latest updates regardless of using proxy or not ... on the package version 1.2.2 it works fine.

> Failed to get Proxy IP 

```
Fingerpring loaded
D:\Path\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:32
      if (error) throw new Error(error);
                       ^

Error: Failed to get proxy ip
    at D:\Path\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:32:24
```

**Comment by bablosoft** [comment]
Hi,

This error means that proxy external ip couldn't be resolved.

Please ensure that proxies are working and there is no connection issues.

Attach result of execution

```curl -v ip.bablosoft.com```

Attach the minimal source code to reproduce the issue.

**Comment by EliteDev2** [comment]
Here is the result of  **curl -v ip.bablosoft.com** 
```
StatusCode        : 200
StatusDescription : OK
Content           : 2405:201:682f:102e:2d5e:d78d:3132:f0d4
RawContent        : HTTP/1.1 200 OK
                    2405:201:682f:102e:2d5e:d78d:3132:f0d4
Forms             : {}
Headers           : {[Connection, close], [Content-Length, 38], [Content-Type, text/plain], [Date, Mon, 31 Jul 2023 15:04:16 GMT]...}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 38
```
As it turns out, the  Browser profiles which i created in engine version **25.5.0** were giving this IP error on the latest engine **26.0.2**.
Deleting those profiles and creating new one on 26.0.2 with same fingerprint worked but I had to login again on my services which could cause some suspecious activity in future.

As for the Sample code, I used the example code in your documentation to test my previous profiles and the issue only occured on those profiles. Newly created profiles on **25.5.0** is running fine on the **26.0.2** but not the older profiles which i have been using from past 1 month.

**Comment by bablosoft** [comment]
Thanks, I'll take a look a liitle bit later

**Comment by ClassAxion** [comment]
I also got the same problem when updated from `25.5.0` to `26.0.2`. 
Previous version support needs to be maintained because I use it for such purposes that I can't just delete the profile and login again, as @EliteDev2 said, this could cause some suspecious activity in future

**Comment by EliteDev2** [comment]
Even after deleting the profile and the problem comes back after few runs of the newly created Profile. 
So the only  two option left is to create new profile after every few runs OR just switch back to **25.5.0**. I had to go with the 2nd option. Hope this will be fixed soon 👍

**Comment by bablosoft** [comment]
The error `Failed to get proxy ip` can happen if and only if http request to following url http://ip.bablosoft.com was unsuccessful with curl through specified proxy.

So the issue is either with connection or more likely with proxy.

This is well tested and haven't changed for long.

If you have checked proxy with curl and 100% sure that works and allows traffic to http://ip.bablosoft.com, please send it to mail.totwaego@gmail.com.
