### ISSUE TITLE
Proxy don't work at all

### ISSUE THREAD

**Issue by ClassAxion** [CheshireCaat/puppeteer-with-fingerprints#38]
Proxy don't work when I'm using `useProxy('socks5://127.0.0.1:8080')` or even with `args: ['--proxy-server=socks://127.0.0.1:8080']`. 

The proxy works fine when I'm requesting it via `curl -x socks5://127.0.0.1:8080 https://api.ipify.org/` or with `axios`

I'm using latest version of the package and engine

**Comment by bablosoft** [comment]
Hi, tested with `socks5://127.0.0.1:11185` provided through ssh tunnel. Can't reproduce.

Please provide full source.

Define what is "don't work"

Also what is result with same proxy using BAS?

**Comment by ClassAxion** [comment]
I also cannot reproduce it for now using below code:

```
const { plugin } = require("puppeteer-with-fingerprints");

(async () => {
    const p = plugin.useProxy("socks5://192.168.10.65:8001");

    const browser = await p.launch({
        headless: false,
    });

    const page = await browser.newPage();

    await page.goto("https://api.ipify.org/");
})();
```

I will check if I really have the latest version on my production software
