### ISSUE TITLE
Can not save login cookies

### ISSUE THREAD

**Issue by undefinedteam1** [CheshireCaat/puppeteer-with-fingerprints#4]
Hi, 
I'm login with user/pass on the website, but when me open again profile folder then all cookies not found and require login again.
Can you check for me?
Thanks

```js
    let plugin = createPlugin(puppeteer)
    plugin.useFingerprint((await fsPromises.readFile(`fp_win/fp_${account.fp}.fp`)).toString())
    plugin.useProxy(account.proxy)

    const browser = await plugin.launch({
        headless : false,
        args : [`--user-data-dir=C:\\workspace\\fingerprint-switcher\\profiles\\p_${account.id}_p`]
    });
```

**Comment by minhdv92** [comment]
hi @sergerdn, 
I want set my cookie from file to the page and keep it store on profile folder.
But when I open again, its not

Example:

```js
async function feedAccount(account) {
    let plugin = createPlugin(puppeteer)
    plugin.useFingerprint((await fsPromises.readFile(`fp_win/fp_${account.fp}.fp`)).toString())
    plugin.useProxy(account.proxy)

    const browser = await plugin.launch({
        headless : false,
        args : [`--user-data-dir=C:\\workspace\\fingerprint-switcher\\profiles\\p_${account.id}_p`]
    });
    let [page] = await browser.pages();
    const cursor = createCursor(page)
    await page.setDefaultNavigationTimeout(0);
    await page.setCookie(...JSON.parse(account.cookies))

    await page.goto('https://facebook.com');
    await sleep(5000)

    if(await page.$("#email")) {
        await cursor.click('#email')
        await page.type('#email', account.email, {delay: 100});
        await cursor.click('#pass')
        await page.type('#pass', account.password, {delay: 100});
        await cursor.click('#loginbutton')
        await sleep(5000)
    }

    if(!await page.$('form[action^="/logout"]')) {
        await mysql.updateStatus(account.id, account.pid, "NOT_LOGIN")
        await browser.close()
        return
    }

    await autoScrollDown(page, 50)
    await sleep(1 * 60 * 1000)
    await autoScrollUp(page, 50)
    await sleep(5 * 60 * 1000)

    const client = await page.target().createCDPSession();
    const cookies = (await client.send('Network.getAllCookies')).cookies;

    await mysql.updateStatus(account.id, account.pid, "OK")
    await mysql.updateCookies(account.id, account.pid, JSON.stringify(cookies))
    await browser.close()
}
```

**Comment by lechuhuuha** [comment]
> Hi, I'm login with user/pass on the website, but when me open again profile folder then all cookies not found and require login again. Can you check for me? Thanks
> 
> ```js
>     let plugin = createPlugin(puppeteer)
>     plugin.useFingerprint((await fsPromises.readFile(`fp_win/fp_${account.fp}.fp`)).toString())
>     plugin.useProxy(account.proxy)
> 
>     const browser = await plugin.launch({
>         headless : false,
>         args : [`--user-data-dir=C:\\workspace\\fingerprint-switcher\\profiles\\p_${account.id}_p`]
>     });
> ```

Hi @minhdv92 i'm also a nodejs dev from vietnam. Do you mind if i could discuss more about puppeteer. 
Here is my tg account : https://t.me/huuhazozo
Thanks

**Comment by developers-dev** [comment]
@sergerdn 
thanx sir
I tried with the code above and tested it.
However, the fingerprint.json file generated by the above code and
I noticed that the fingerprint.json file I have is slightly different.
It's too long to show them all, but my json file is in the following format.
My file starts with {"canvas..., but the file generated by the code above starts with {\"valid\":true,\"plugins\"..

my fingerprint.json file..

`{"canvas":true,"webgl":true,"audio":true,"battery":true,"rectangles":true,"perfectcanvas":true,"sensor":false,"font_data":true,"fingerprint":"{\"valid\":true,\"plugins\":[{\"ref\":1446158656,\"description\":\"Portable Document Format\",\"filename\":\"internal-pdf-viewer\",\"name\":\"PDF Viewer\",\"mimes\":[-1248334925,-1004735216]},{\"ref\":1010824838,\"description\":\"Portable Document Format\",\"filename\":\"internal-pdf-viewer\",\"name\":\"Chrome PDF Viewer\",\"mimes\":[-1248334925,-1004735216]},{\"ref\":-1972253206,\"description\":\"Portable Document Format\",\"filename\":\"internal-pdf-viewer\",\"name\":\"Chromium PDF Viewer\",\"mimes\":[-1248334925,-1004735216]},{\"ref\":-545395695,\"description\":\"Portable Document Format\",\"filename\":\"internal-pdf-viewer\",\"name\":\"Microsoft Edge PDF Viewer\",\"mimes\":[-1248334925,-1004735216]},{\"ref\":1114102244,\"description\":\"Portable Document Format\",\"filename\":\"internal-pdf-viewer\",\"name\":\"WebKit built-in PDF\",\"mimes\":[-1248334925,-1004735216]}],\"mimes\":[{\"ref\":-1248334925,\"description\":\"Portable Document Format\",\"suffixes\":\"pdf\",\"type\":\"application/pdf\",\"plugin\":1446158656},{\"ref\":-1004735216,\"description\":\"Portable Document Format\",\"suffixes\":\"pdf\",\"type\":\"text/pdf\",\"plugin\":1446158656}],\"ua\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36\",\"tags\":[\"Microsoft Windows\",\"Chrome\",\"Desktop\",\"Windows 10\"],\"dnt\":false,\"width\":1920,\"height\":937,\"canvas\":\"7127f7b4ac16bc388841d5b28b9d27987446c0baf9df5b797c29e5983714d96811ab0fa38352d4c7f1aa9e50ff1261ff38a5f30cd6d2783ba25f44fb91308e05837b7d7c827d7f83807d7e827c7f7d7e7e827b807e7d7c828181838283827c7f8280807d7d82807c817d7b828381837b7d7f82\",\"webgl\":\"3aa51522ed7a2dcbfc76c73268139ffca5c72af530295f9cf3d06f9a3c36f1d3383a77555091479ef90c555f75d8ed2302d45b4f42655cf93174cf7e63991608837b7d7c827d7f83807d7e827c7f7d7e7e827b807e7d7c828181838283827c7f8280807d7d82807c817d7b828381837b7d7f82\",\"rectangles\":\"5c1a26599159de98bf93bf62b2e6f0c6d340c6e8fe5bb981ba5cac17ec7af7d448501bd6f84c87cadf70222f62d9df2fbf4ec744ca8dc44ae7f04b9f2d7d800766600100aaf206009ac90500ff5cf9fff6fc02007ce20300a824f9ffc103040065160000e760f9ff6570020058a9060090a40100e9bc0100aed106007cf5fdff0af200001329060009470400d052f9ff45b302006f9afaffd08afeffb7c7fcff33affeff03befbfff59bffff4b190100e7d4ffff2b1ffffff4540400428e0100dfcafbffb8aafaffacd7000056d4fbff364c000002890300398a030045b0f8ff22f50300000c0300c7a3feff0b07faffce71f9ffd51dfeffc989fbff93a30200b678faff7307fbff9714fcff228a0100d242070057e50100f950feffac60fbff0588f8ff6438fcff362803004a1001006df604005edbf8ff405effffe6350100633e1e0e203e1e0e203e1e0e203e1e0e633e1e0e\",\"audio\":\"4d1b302da6de871e2b5d4fd1fd76f04334baaff478884604c42e80192888ef436158a6765f6d578930bbb377de11ce6328db49692ae55bf442d7f7a42547540a76737b8587938571836f6c908b6e73937c74827891758781797d937981796f798c936f8f8a7c908b837b6e747e7f7082746c778e778c7c806f756d85867a7a7592758c857285908c7790806e826b917b7a83809382768a746d8f7b738d706b749085906c\",\"battery\":\"d5162d05bc06b1950c7ed025cc49a9361188d7066e589d4a3a9bc80eff681e34df5b9bd641d26bab25e73fb30bac9060b93d99b4446f15a57af3827ab105560113255bb1281156\",\"has_battery_api\":true,\"has_battery_device\":false,\"webgl_properties\":{\"unmaskedVendor\":\"Google Inc. (NVIDIA)\",\"unmaskedRenderer\":\"ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)\",\"vendor\":\"WebKit\",\"renderer\":\"WebKit WebGL\",\"shadingLanguage\":\"WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)\",\"version\":\"WebGL 1.0 (OpenGL ES 2.0 Chromium)\",\"maxAnisotropy\":\"16\",\"shadingLanguage2\":\"WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)\",\"version2\":\"WebGL 2.0 (OpenGL ES 3.0 Chromium)\",\"aliasedLineWidthRange\":{\"0\":1,\"1\":1},\"aliasedPointSizeRange\":{\"0\":1,\"1\":1024},\"alphaBits\":\"8\",\"blueBits\":\"8\",\"depthBits\":\"24\",\"greenBits\":\"8\",\"maxCombinedTextureImageUnits\":\"32\",\"maxCubeMapTextureSize\":\"16384\",\"maxFragmentUniformVectors\":\"1024\",\"maxRenderBufferSize\":\"16384\",\"maxTextureImageUnits\":\"16\",\"maxTextureSize\":\"16384\",\"maxVaryingVectors\":\"30\",\"maxVertexAttribs\":\"16\",\"maxVertexTextureImageUnits\":\"16\",\"maxVertexUniformVectors\":\"4095\",\"maxViewportDims\":{\"0\":32767,\"1\":32767},\"redBits\":\"8\",\"stencilBits\":\"8\",\"subpixelBits\":\"4\",\"sampleBuffers\":\"1\",\"samples\":\"4\",\"stencilBackValueMask\":\"2147483647\",\"stencilBackWritemask\":\"2147483647\",\"stencilValueMask\":\"2147483647\",\"stencilWritemask\":\"2147483647\",\"maxColorAttachmentsWebgl\":\"8\",\"maxDrawBuffersWebgl\":\"8\",\"webglContextAttributesDefaults\":{\"alpha\":true,\"antialias\":true,\"depth\":true,\"desynchronized\":false,\"failIfMajorPerformanceCaveat\":false,\"powerPreference\":\"default\",\"premultipliedAlpha\":true,\"preserveDrawingBuffer\":false,\"stencil\":false,\"xrCompatible\":false},\"extensions\":`

**Comment by bablosoft** [comment]
Posting fingerprints is not allowed

**Comment by developers-dev** [comment]
sorry. I'm new to Github so I didn't know much about it.
