### ISSUE TITLE
potato

### ISSUE THREAD

**Issue by invisivel73** [CheshireCaat/puppeteer-with-fingerprints#46]
great update, now the browser has turned into a potato.

<img width="689" alt="good" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/18131396/458a0bd5-4a0a-42ba-bccc-d8b46bba6519">

the commands just don't work anymore

<img width="468" alt="good1" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/18131396/f762bd7f-3996-4abe-8ca8-10c00b407fd1">

**Comment by bablosoft** [comment]
I can't reproduce the issue. Please reopen if you will have minimal source code.

**Comment by invisivel73** [comment]
<img width="607" alt="good2" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/18131396/5e473d2a-445b-40b7-bda4-b6874cd8ed09">

the browser is "frozen"

<img width="801" alt="good3" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/18131396/d13dd76e-3884-4102-bb4c-b8fa5c760986">

**Comment by invisivel73** [comment]
page.goto() not work.
