### ISSUE TITLE
Tips for improving stealthiness + integration

### ISSUE THREAD

**Issue by victor10100111001** [CheshireCaat/puppeteer-with-fingerprints#47]
This is probably the most stealthy browser automation tool that i have seen. I am curious if you recommend any other optimizations for improving stealthiness like puppeteer-extra-plugin-stealth? Is it possible to use puppeteer-extra plugins with this library?

I can see that this library is only a few months old. Is it common for the library to get detected by cloudflare, datadome, etc or has it been smooth sailing?

**Comment by bablosoft** [comment]
> I am curious if you recommend any other optimizations for improving stealthiness like puppeteer-extra-plugin-stealth?

Use PerfectCanvas

https://wiki.bablosoft.com/doku.php?id=perfectcanvas

FontPack 

https://wiki.bablosoft.com/doku.php?id=FontPack

etc

> Is it possible to use puppeteer-extra plugins with this library?

No, replacing browser properties with js could be detected, don't do that.

> Is it common for the library to get detected by cloudflare, datadome, etc or has it been smooth sailing?

Cloudflare is tested and works correctly, datadome is not  tested, if you have any issues, please use this template to report

https://community.bablosoft.com/topic/12199/researching-sites-protection
