### ISSUE TITLE
Unsupported OS platform for named mutex

### ISSUE THREAD

**Issue by mdwitr0** [CheshireCaat/puppeteer-with-fingerprints#5]
Library doesn't working on arm processors.

```
throw new Error('Unsupported OS platform for named mutex.');
          ^
Error: Unsupported OS platform for named mutex.
```

Platform: ARM
OS: Mac OS
CPU: M1

**Comment by CheshireCaat** [comment]
Docs:
- [Architecture](https://github.com/CheshireCaat/puppeteer-with-fingerprints#architecture)
- [Installation](https://github.com/CheshireCaat/puppeteer-with-fingerprints#installation)

Issues:
- https://github.com/CheshireCaat/playwright-with-fingerprints/issues/1
- https://github.com/CheshireCaat/selenium-with-fingerprints/issues/7

Will this information be enough?

**Comment by mdwitr0** [comment]
Thanks)
