### ISSUE TITLE
Error: Failed to launch the browser process! [0913/084300.624:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Users\asas\Desktop\xm\data\run\FingerprintPluginV4\f0036\browser.5\worker\chrome\chrome.dll: The specified procedure could not be found. (0x7F)

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [CheshireCaat/puppeteer-with-fingerprints#51]
Error: Failed to launch the browser process!
[0913/084300.624:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Users\asas\Desktop\xm\data\run\FingerprintPluginV4\f0036\browser.5\worker\chrome\chrome.dll: The specified procedure could not be found. (0x7F)

how can i solve this error please 

my os is windows 8.1 ?

**Comment by bablosoft** [comment]
Google Chrome is not available on 8.1.

https://support.google.com/chrome/a/answer/7100626?hl=en

**Comment by ahmedabdelhamedz** [comment]
> Google Chrome is not available on 8.1.
> 
> https://support.google.com/chrome/a/answer/7100626?hl=en

`const { plugin } = require('puppeteer-with-fingerprints');

(async () => {
  // Get a fingerprint from the server:
  const fingerprint = await plugin.fetch('', {
    tags: ['Microsoft Windows', 'Chrome'],
  });

  // Apply fingerprint:
  plugin.useFingerprint(fingerprint);

  // Launch the browser instance:
  const browser = await plugin.launch({
    executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe',
    headless:false
});

  // The rest of the code is the same as for a standard `puppeteer` library:
  const page = await browser.newPage();
  await page.goto('https://browserleaks.com/canvas');
  //await page.goto('https://bot.sannysoft.com');

  // Print the browser viewport size:
  console.log(
    'Viewport:',
    await page.evaluate(() => ({
      deviceScaleFactor: window.devicePixelRatio,
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
    }))
  );

  await browser.close();
})();`

i know that becuase my chrome version is 109 i make an executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', as you see in a code above it works with puppeteer-extra and puppeteer packages but when i use it with puppeteer-with-fingerprints it didnt work can i know reason please 

how can i solve that with your package?

**Comment by bablosoft** [comment]
Please update OS

**Comment by ahmedabdelhamedz** [comment]
> Please update OS

i can not update OS now becuase my laptop specs core i3 and ram 4 gb can not accept windows 10 

is there a solution to make executable path work with your package please ?

**Comment by bablosoft** [comment]
No
