### ISSUE TITLE
ENOTACQUIRED After few runs

### ISSUE THREAD

**Issue by xploader** [CheshireCaat/puppeteer-with-fingerprints#59]
Please help after few runs 2-10 minutes I get this error
```
node:internal/event_target:1084
  process.nextTick(() => { throw err; });
                           ^
Error: Lock is not acquired/owned by you
    at C:\Users\Administrator\Desktop\cleanJSCR\node_modules\proper-lockfile\lib\lockfile.js:285:43
    at LOOP (node:fs:2816:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ENOTACQUIRED'
}

Node.js v21.0.0
```

This is the starting worker file: 
```
const { Worker, isMainThread, workerData } = require('worker_threads');
const configFile = 'Config_app.json';
const fs = require('fs');
const config = JSON.parse(fs.readFileSync(configFile));
const instance_list = config.BotInstances;

const workerScript = './g2.js'

if (isMainThread) {
    async function StartWorker(ip, instance) {
      const worker = new Worker(workerScript, { workerData: { ip, instance } });
  
      worker.on('message', (result) => {
        console.log(result);
        
        StartWorker(ip, instance);
      });
    }

    for (const instance of instance_list) {
      StartWorker(instance.ip, instance.instance);
    }
  }
```

and the worker file:

```
const   dd = require('./Modules/delf')
const { parentPort,workerData } = require('worker_threads');

const { ip, instance } = workerData;
console.log(workerData);

async function runFunction(ip, instance) {
    const {plugin} = require('puppeteer-with-fingerprints'); 
    plugin.setWorkingFolder(`./engine_br/${instance}`);
    let path_prof = `./engine_br/${instance}/profiles`;
    await dd(path_prof);
    let browser;
    console.log(`'Instance:${instance}, ip: ${ip}`);

    try{
        const fingerprint = await plugin.fetch('someKey', {
            tags: ['Microsoft Windows', 'Chrome']
            });
        console.log('Time to sleep!');
        
        browser = await plugin.useFingerprint(fingerprint).launch(
            {headless:false,            
            }); 
        const page = await browser.newPage();
        await page.goto('https://google.com')
        
    }
    catch(error){
        console.log(error);
    }
    finally{  
        try{
            console.log('Try to close browser..');
            if (browser){
                await browser.close();
            }
            
        }
        catch(error){
            console.log(error)
        }      
        }

    };
async function main_r(resolve){
    await runFunction(ip, instance);
    resolve();
    parentPort.postMessage('DONE');
}
new Promise(resolve =>main_r(resolve))

```
*I delete the profiles folder  await dd(path_prof); when worker is starting
Even if I'm running just 1 instance worker I still get the error.

**Comment by CheshireCaat** [comment]
I haven’t tested your code yet, but I can recommend that when you finish working in the worker, forcefully shut it down using `worker.terminate()`, for example:

```js
worker.on('message', (result) => {
  if (result === 'DONE') {
    worker.terminate();
  }
});
```

You create them but don't unref or force shutdown, chances are that when you run them again they might still be running and taking up resources.

In general, judging by your code, upon receiving a message from a worker you launch another one, exactly the same, with the same data - this is incorrect. Please think through the logic better, I can't help you adjust the code for multithreading logic.

**Comment by xploader** [comment]
> I haven’t tested your code yet, but I can recommend that when you finish working in the worker, forcefully shut it down using `worker.terminate()`, for example:
> 
> ```js
> worker.on('message', (result) => {
>   if (result === 'DONE') {
>     worker.terminate();
>   }
> });
> ```
> 
> You create them but don't unref or force shutdown, chances are that when you run them again they might still be running and taking up resources.
> 
> In general, judging by your code, upon receiving a message from a worker you launch another one, exactly the same, with the same data - this is incorrect. Please think through the logic better, I can't help you adjust the code for multithreading logic.

Looks like it's running well if I terminate worker as you sugested. Thanks. I changed the logic loop inside the worker instead of stoping and starting workers. Thanks for the help

**Comment by CheshireCaat** [comment]
Great, if your problem is resolved for now, please close the ticket.
