### ISSUE TITLE
Error: Failed to get proxy ip

### ISSUE THREAD

**Issue by marcusdiy** [CheshireCaat/puppeteer-with-fingerprints#60]
I'm using puppeteer with fingerprints and getting this error that wont allow the process to start.
I have a paid key and it worked until a couple hours ago. I tried changing my ip and it didnt solve.

Exception has occurred: Error: Failed to get proxy ip
at C:\xxxxx\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:40:24

**Comment by bablosoft** [comment]
"Failed to get proxy IP" means that request to http://ip.bablosoft.com/ failed through curl and specified proxy.

**Comment by marcusdiy** [comment]
Sure, thanks it seems like a problem with IPRoyale sticky sessions

**Comment by marcusdiy** [comment]
Now it doesnt work again, not using proxies

Waiting for the debugger to disconnect...
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 51.38.126.82:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '51.38.126.82',
  port: 443
}

Node.js v18.12.0

**Comment by marcusdiy** [comment]
Reverse ip points to bablosoft.com. Changed ip now it works again. Is there some firewall rule that limits ips?

**Comment by marcusdiy** [comment]
This error keeps happening again and again and there is no stable fix. What process does that call? Can it be replaced?

**Comment by bablosoft** [comment]
In order to fix it, please update to latest version and use single process.
