### ISSUE TITLE
browser not start

### ISSUE THREAD

**Issue by xlskk** [CheshireCaat/puppeteer-with-fingerprints#61]
`C:\Users\ZGEN\Desktop\price_bot\node_modules\bas-remote-node\src\services\socket.js:53
          reject(new Error(`Cannot connect to the WebSocket server (reason: ${error.reason})\n${INVALID_ENGINE_ERROR}`));
                 ^

Error: Cannot connect to the WebSocket server (reason: connection failed)
This could be due to the fact that the engine was not downloaded or unpacked correctly.
Try completely deleting the engine folder and restarting the code until it completes.
If this does not help, open an issue with a detailed description of the problem.
    at C:\Users\ZGEN\Desktop\price_bot\node_modules\bas-remote-node\src\services\socket.js:53:18
    at Timeout._onTimeout (C:\Users\ZGEN\Desktop\price_bot\node_modules\chnl\dist\channel.cjs.js:2:4848)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)`

i had an error when start program. i have access key. please help

**Comment by Pairs34** [comment]
Same Problem,

**Comment by Pairs34** [comment]
Same problem

**Comment by ngdekhai** [comment]
Same problem, how to solve this?

**Comment by CheshireCaat** [comment]
The error contains a fairly detailed explanation - you need to try deleting the folder with the engine and downloading it again. The message also contains a request to provide detailed information that no one provided as part of this ticket, at a minimum - plugin version, puppeteer version, code examples.

I've checked examples from the repository and run tests several times in the last few days - can't replicate the problem. Open a ticket when more details are available.

**Comment by TheGP** [comment]
For me it helped to remove data dir + npm uninstall puppeteer-with-fingerprints and install it again.
