### ISSUE TITLE
 Error: Unable to start engine process (code: 3221225781)

### ISSUE THREAD

**Issue by soroka41** [CheshireCaat/puppeteer-with-fingerprints#63]
throw new Error(`Unable to start engine process (code: ${error.code})\n${INVALID_ENGINE_ERROR}`);
          ^

Error: Unable to start engine process (code: 3221225781)
This could be due to the fact that the engine was not downloaded or unpacked correctly.
Try completely deleting the engine folder and restarting the code until it completes.
If this does not help, open an issue with a detailed description of the problem.

**Comment by DREW2212** [comment]
same issue. plz help

**Comment by CheshireCaat** [comment]
Duplicate issue - https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/61
