### ISSUE TITLE
The browser is downloading - this may take some time.

### ISSUE THREAD

**Issue by dindamb** [CheshireCaat/puppeteer-with-fingerprints#71]
i just download : http://downloads.bablosoft.com/distr/FastExecuteScriptProtected64/26.0.2/FastExecuteScriptProtected.x64.zip

and put on my projectfolder\data\engine

why when i run the sample script. it always do browser downloading ?

how to solve that ?

**Comment by CheshireCaat** [comment]
This happens because the plugin uses a specific version of the engine, you cannot choose it yourself. The current version is **26.4.0**, so if you want to download and use it that way, that's the only version that's available.
