### ISSUE TITLE
The plugin does not activate proxies, although they work.

### ISSUE THREAD

**Issue by el9in** [CheshireCaat/puppeteer-with-fingerprints#72]
The plugin does not activate proxies, although they work.

When passing a proxy to the script, it does not go to the page, there are suspicions that it cannot connect the proxy due to some internal conflicts, and it does not return an error, but only endless loading of the page.

If you access the proxy directly, they work correctly.

**Comment by bablosoft** [comment]
Please send proxy here mail.to.twaego@gmail.com

**Comment by el9in** [comment]
> Please send proxy here [mail.to.twaego@gmail.com](mailto:mail.to.twaego@gmail.com)

They are tied to the IP.

**Comment by bablosoft** [comment]
Hard to help without proxy.

**Comment by el9in** [comment]
I can link a proxy to your IP, but to do this, write to me in tg t.me/el9in. For about 20 minutes.
