### ISSUE TITLE
Change the Screen Size

### ISSUE THREAD

**Issue by dindamb** [CheshireCaat/puppeteer-with-fingerprints#73]
i test select device mobile,chrome.
and this the screenshot view in my computer.
How can i change the screen, with normal size or custom size view in computer ?.

<img width="960" alt="wholescreen" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/18514102/b305fc15-e0ae-4efa-854d-1973a5493e34">

**Comment by artickc** [comment]
await plugin.useFingerprint(await readFile(fingerprint, 'utf8'), {
    emulateDeviceScaleFactor: false
  });

**Comment by dindamb** [comment]
> ```
> await plugin.useFingerprint(await readFile(fingerprint, 'utf8'), {
>     emulateDeviceScaleFactor: false
>   });
> ```

thanks, it's perfect
