### ISSUE TITLE
fingerprint.com doesn't trust me

### ISSUE THREAD

**Issue by kansiliyundi** [CheshireCaat/puppeteer-with-fingerprints#75]
When I use the api service provided by fingerprint.com, he can accurately detect that I am coming from browserAutomationStudio
"bot": {
        "result": "bad",
        "type": "browserAutomationStudio"
      },

**Comment by bablosoft** [comment]
Can you attach more info, how it could be reproduced?

**Comment by kansiliyundi** [comment]
Here are the test results
![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/15216459/49d0a44e-2e82-4348-8188-92c72b0135f9)

This is the returned data
 `{
  "identification": {
    "data": {
      "visitorId": "mcVfvEs9eWjEDzWjJYQj",
      "requestId": "1706783240655.EUdtQa",
      "browserDetails": {
        "browserName": "Chrome",
        "browserMajorVersion": "118",
        "browserFullVersion": "118.0.0",
        "os": "Windows",
        "osVersion": "10",
        "device": "Other",
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
      },
      "incognito": false,
      "ip": "47.99.191.21",
      "timestamp": 1706783240663,
      "time": "2024-02-01T10:27:20Z",
      "url": "https://aaa.zhaomm.top/",
      "tag": {},
      "confidence": {
        "score": 0.7
      },
      "visitorFound": false,
      "firstSeenAt": {
        "global": "2024-02-01T10:27:20.663Z",
        "subscription": "2024-02-01T10:27:20.663Z"
      },
      "lastSeenAt": {
        "global": null,
        "subscription": null
      }
    }
  },
  "botd": {
    "data": {
      "bot": {
        "result": "bad",
        "type": "browserAutomationStudio"
      },
      "url": "https://aaa.zhaomm.top/",
      "ip": "47.99.191.21",
      "time": "2024-02-01T10:27:20.684Z",
      "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
      "requestId": "1706783240655.EUdtQa"
    }
  },
  "rootApps": {
    "data": {
      "result": false
    }
  },
  "emulator": {
    "data": {
      "result": false
    }
  },
  "ipInfo": {
    "data": {
      "v4": {
        "address": "47.99.191.21",
        "geolocation": {
          "accuracyRadius": 1000,
          "latitude": 30.2994,
          "longitude": 120.1612,
          "timezone": "Asia/Shanghai",
          "city": {
            "name": "Hangzhou"
          },
          "country": {
            "code": "CN",
            "name": "China"
          },
          "continent": {
            "code": "AS",
            "name": "Asia"
          },
          "subdivisions": [
            {
              "isoCode": "ZJ",
              "name": "Zhejiang"
            }
          ]
        },
        "asn": {
          "asn": "37963",
          "name": "Hangzhou Alibaba Advertising Co.,Ltd.",
          "network": "47.96.0.0/12"
        },
        "datacenter": {
          "result": true,
          "name": "Alibaba Cloud"
        }
      }
    }
  },
  "vpn": {
    "data": {
      "result": false,
      "originTimezone": "Asia/Shanghai",
      "originCountry": "unknown",
      "methods": {
        "timezoneMismatch": false,
        "publicVPN": false,
        "auxiliaryMobile": false
      }
    }
  },
  "incognito": {
    "data": {
      "result": false
    }
  },
  "tampering": {
    "data": {
      "result": false,
      "anomalyScore": 0
    }
  },
  "clonedApp": {
    "data": {
      "result": false
    }
  },
  "factoryReset": {
    "data": {
      "time": "1970-01-01T00:00:00Z",
      "timestamp": 0
    }
  },
  "jailbroken": {
    "data": {
      "result": false
    }
  },
  "frida": {
    "data": {
      "result": false
    }
  },
  "privacySettings": {
    "data": {
      "result": false
    }
  },
  "virtualMachine": {
    "data": {
      "result": false
    }
  },
  "locationSpoofing": {
    "data": {
      "result": false
    }
  }
}`

**Comment by bablosoft** [comment]
Ok, but do I get these results? Any steps to reproduce?

**Comment by kansiliyundi** [comment]
Yes, you can build a website, use the api provided by fingerprint.com, view it on their dashboard, and they offer a 14-day free trial

**Comment by bablosoft** [comment]
Tested on BAS 26.7.0 version, it works even without PerfectCanvas.

Please ensure, that this bug is being reproduced in latest BAS version, if yes, please attach the project.

Please avoid putting your FingerprintSwitcher key there, just leave a blank line

<img width="1524" alt="firefox_2024-02-01_13-23-51" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/19365536/67773553-ad55-480e-b4e3-62c5b75fcf97">

**Comment by kansiliyundi** [comment]
No, I used puppeteer-with-fingerprint 1.5.4 Free version，I need to test it out before I buy it，Only simple code is used

const fingerprint = await plugin.fetch('', {
            tags: ['Microsoft Windows', 'Chrome'],
          }); 

plugin.useFingerprint(fingerprint);  

const browser = await plugin.launch(browserOptions);

**Comment by bablosoft** [comment]
It seems that this issue happens on older BAS version.

We will update puppeteer-with-fingerprints to latest version.

Meanwhile you can use BAS.

**Comment by bablosoft** [comment]
Please update package and try again, it is fixed.
