### ISSUE TITLE
Unable to use in Linux

### ISSUE THREAD

**Issue by LuisRibeiro-nBanks** [CheshireCaat/puppeteer-with-fingerprints#76]
I am trying to use this package in a scrapping solution, but my docker runs using Linux, and when trying to build the image, I am getting an error related to "browser-with-fingerprints":

23.11 npm ERR! code EBADPLATFORM
23.14 npm ERR! notsup Unsupported platform for browser-with-fingerprints@1.5.4: wanted {"os":"win32","arch":"ia32,x64"} (current: {"os":"linux","arch":"x64"})
23.14 npm ERR! notsup Valid OS:    win32
23.14 npm ERR! notsup Valid Arch:  ia32,x64
23.14 npm ERR! notsup Actual OS:   linux
23.14 npm ERR! notsup Actual Arch: x64

Is there any solution for this? If not, is it possible to consider an alternative allowing this package to be run in Linux?

**Comment by CheshireCaat** [comment]
Please check https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/70.

For the docker, you can try windows images, but working with it has not been tested, and there are no guarantees that everything will work correctly.
