### ISSUE TITLE
puppeteer-with-fingerprints detect botd browserAutomationStudio

### ISSUE THREAD

**Issue by vpolonic** [CheshireCaat/puppeteer-with-fingerprints#77]
Are you still working on your products or do we have to look for other solutions?
![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/45886702/689d03ea-d900-49ea-8d61-a76ddadb1cdd)

**Comment by bablosoft** [comment]
If you are talking about fingerprint com, it has been fixed 5 days ago.

Please ensure, that you are using 1.4.5.

<img width="1389" alt="worker_2024-02-06_19-13-21" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/19365536/44b84736-61fd-41d2-9277-d4fa80d14230">

If it still reproduces on your side, please attach steps to reproduce.
