### ISSUE TITLE
Different browser version

### ISSUE THREAD

**Issue by omar6995** [CheshireCaat/puppeteer-with-fingerprints#78]
Hi everyone, I'm trying the puppeteer with fingerprint library before going with the fingerprintswitcher.

However , when I try to see if I get detected by https://www.browserscan.net/ I get this result : 

![image](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/13081965/975fa849-7459-420a-bdd4-485d28ecdc84)

Is it normal?

**Comment by bablosoft** [comment]
Please attach exact code and send fingerprint to [mail.to.twaego@gmail.com](mailto:mail.to.twaego@gmail.com)
