### ISSUE TITLE
Fetch Error

### ISSUE THREAD

**Issue by swassapparel21** [CheshireCaat/puppeteer-with-fingerprints#8]
Just want to ask is this with regards to the free version? Will this error be gone if I upgraded to premium?

![Capturesss](https://user-images.githubusercontent.com/130437011/231074598-6bc41a06-8229-4780-a505-f8a4a6db9d25.JPG)

**Comment by swassapparel21** [comment]
@sergerdn I always encounter this, do you mean network error on my side?

**Comment by swassapparel21** [comment]
I thought this is a request limit of the free version

**Comment by Motivationking** [comment]
same error here, some times its fetched successfully, but every times fetching takes more then 5 minutes per fingerprints... why its happening, and how to resolve it

**Comment by Motivationking** [comment]
Yes, i used key also

**Comment by Motivationking** [comment]
I don't think its hard to read a code for me even if its ugly. if you don't
want to share it, i don't mind 😊🤗

**Comment by CheshireCaat** [comment]
For various reasons, it may take longer than usual to receive your fingerprint.

By default, a timeout of 5 minutes is set for obtaining a fingerprint - as an average value, which is usually enough.

If for some reason you are getting an error, right now you can increase the timeout in milliseconds by changing the environment variable:

```js
process.env.FINGERPRINT_TIMEOUT = 360_000; // 6 minutes
```

If this does not solve the problem, please provide more details. For now, I consider the ticket closed.
