### ISSUE TITLE
Error: Lock is not acquired/owned by you - ENOTACQUIRED

### ISSUE THREAD

**Issue by omar6995** [CheshireCaat/puppeteer-with-fingerprints#80]
I'm trying to run multiple instance of puppeteer so I can speed up my scraping task but I constantly get this error:

Error: Lock is not acquired/owned by you
    at C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\proper-lockfile\lib\lockfile.js:285:43
    at LOOP (node:fs:2833:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ENOTACQUIRED'

I've tried to assign to each instance a separate userDataDir in the init method but I still get this error.

Here is the code

browser.js - the class using puppeteer with fingerprint
```
export default class Browser extends EventEmitter {
  constructor(id = 0) {
    super();
    this.id = id;
    this.browser = null;
  }
  getNextProxy() {
    const randomIndex = Math.floor(Math.random() * proxies.length);
    return proxies[randomIndex];
  }

  async init(headless = false) {
    const fingerprint = await plugin.fetch(key, { tags: ['Microsoft Windows', 'Chrome'] });
    const proxy = this.getNextProxy();
    plugin.useProxy(proxy, {
      // Change browser timezone according to proxy:
      changeTimezone: true,
      changeBrowserLanguage: true,
      changeGeolocation: true,
      changeWebRTC: true,
      detectExternalIP: true
    });
    //plugin.setWorkingFolder(`./data/${this.id}`);
    this.browser = await plugin
      .useFingerprint(fingerprint)
      .launch({ headless: headless, userDataDir: `./userData/${this.id}` });
  }
```

I'm using a custom dataDir on each call to puppeteer.launch.

and here is my main file main.js

`const browsers = Array.from({ length: 2 }, (_, index) => new Browser(index + 1));
// Initialize all browser instances
await Promise.all(browsers.map(browser => browser.init(true)));`

**Comment by omar6995** [comment]
I have added the following line of code in my init method , which set a new folder for each instance.

`plugin.setWorkingFolder(`./workingFolder/${this.id}`);`

Here is the full init method : 

```
async init(headless = false) {
    const fingerprint = await plugin.fetch(key, { tags: ['Microsoft Windows', 'Chrome'] });
    const proxy = this.getNextProxy();
    plugin.useProxy(proxy, {
      // Change browser timezone according to proxy:
      changeTimezone: true,
      changeBrowserLanguage: true,
      changeGeolocation: true,
      changeWebRTC: true,
      detectExternalIP: true
    });
    plugin.setWorkingFolder(`./workingFolder/${this.id}`);
    plugin.setRequestTimeout(300 * 300000);
    this.browser = await plugin
      .useFingerprint(fingerprint)
      .launch({ headless: headless, userDataDir: `./userData/${this.id}` });
  }
```

However, I get a new error that I didn't got before using a new working directory

```
C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\puppeteer\node_modules\@puppeteer\browsers\lib\cjs\launch.js:267
                reject(new Error([
                       ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\puppeteer\node_modules\@puppeteer\browsers\lib\cjs\launch.js:267:24)      
    at Interface.emit (node:events:530:35)
    at Interface.close (node:internal/readline/interface:527:10)
    at Socket.onend (node:internal/readline/interface:253:10)
    at Socket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
I have adding the ignoreDefaultArgs: ['--disable-extensions'] mentionned in https://pptr.dev/troubleshooting but it still doesnt work.

**Comment by omar6995** [comment]
It seems that the error comes when we use the userDataDir params in the launch method along with the setWorkingFolder method. 

If i remove the userDataDir the script can be launched but I still get the  ENOTACQUIRED error .

**Comment by CheshireCaat** [comment]
Please try to follow rules described [here](https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/58#issuecomment-1773736094).

If your goal is to run multiple instances completely in parallel, I recommend using something like workers to separate them into different processes. Within one process, the work of the plugin is already synchronized, but not for all actions, as I indicated in the link above.

Otherwise, it is advisable to synchronize the work with `setWorkingFolder`, since otherwise race conditions are possible. Thus, at least the process of configuring and launching the browser must be locked, for example through `async-lock` or something similar.

**Comment by omar6995** [comment]
Thanks for your quick reply.

I have added the locking in the init method but I still get the error: Lock is not acquired/owned by you.

Lot of people seems to be asking for this feature of multithreading. Maybe the [examples](https://github.com/CheshireCaat/puppeteer-with-fingerprints/tree/master/examples) can be completed with a code example using one process with async-alock and another example with worker thread ? 

```
async init(headless = false) {
    await lock.acquire('key', async () => {
      const fingerprint = await plugin.fetch(key, { tags: ['Microsoft Windows', 'Chrome'] });
      const proxy = this.getNextProxy();
      plugin.useProxy(proxy, {
        // Change browser timezone according to proxy:
        changeTimezone: true,
        changeBrowserLanguage: true,
        changeGeolocation: true,
        changeWebRTC: true,
        detectExternalIP: true
      });
      //plugin.setWorkingFolder(`./data/${this.id}`);
      console.log(`./workingFolder/${this.id}`);

      plugin.setWorkingFolder(`./workingFolder/${this.id}`);
      plugin.setRequestTimeout(300 * 300000);
      this.browser = await plugin.useFingerprint(fingerprint).launch({
        headless: headless
      });
    });
  }
```

Anyway, thanks again for your help, much appreciated!
