### ISSUE TITLE
PerfectCanvas request takes forever to load

### ISSUE THREAD

**Issue by dr3adx** [CheshireCaat/puppeteer-with-fingerprints#83]
**Reproduction steps:**

go to d1sc0rd.com/register

PerfectCanvas app will record about 50+ requests. I save them all. (should I be saving them all?)
When I try to fetch fingerprint with perfectCanvas parameter in puppeteer-with-fingerprints it will take forever
If i save only 1 out of 50 requests from PerfectCanvas app  then fingerprint fetches normally.

Additional question: when to use precomputed fingerprints and dynamic canvas? its not explained enough in the doc

**Comment by bablosoft** [comment]
You can use native rendering for most of them.

**Comment by dr3adx** [comment]
how do i enable native rendering?

**Comment by bablosoft** [comment]
Disable safeWebGL and safeCanvas params, this will force to use PerfectCanvas, if specific element wasn't found fallback to original.

If these params will be enabled, noise will be added.

**Comment by dr3adx** [comment]
> safeCanvas

ok i will try this, but i still have problem fetching fingerprint with big perfectcanvas app requests? do i use all 55 requests from perfectcanvas app? or just 1?

**Comment by bablosoft** [comment]
You can use native rendering for most of them.

**Comment by dr3adx** [comment]
> You can use native rendering for most of them.

but what do you mean? i dont understand

you mean i should set safeWebGL: false safeCanvas: false and **not use perfectcanvas at all?**

**Comment by bablosoft** [comment]
You need to use only those parts of PerfectCanvas request which has high entropy. Those which are shown on screenshot are not used for fingerprinting with high probability.

**Comment by bablosoft** [comment]
> you mean i should set safeWebGL: false safeCanvas: false and not use perfectcanvas at all?

Of course no.

**Comment by dr3adx** [comment]
> > you mean i should set safeWebGL: false safeCanvas: false and not use perfectcanvas at all?
> 
> Of course no.

no what? im confused now
please tell me what config i need, so i can understand what you mean, like this:

safeCanvas: yes or no?
safeWebGL: yes or no?
perfectCanvas: yes or no?

**Comment by bablosoft** [comment]
You definitely need to use PerfectCanvas. For those items, on screenshot you can use native rendering.

**Comment by dr3adx** [comment]
> You definitely need to use PerfectCanvas. For those items, on screenshot you can use native rendering.

native rendering = safeCanvas: off + safeWebGL: off ? correct ?

**Comment by dr3adx** [comment]
> yes
understood, thank you

https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/4398836/93a8b7c2-e777-4d70-9655-3abd5aa32487

all perfectcanvas requests are same getImageData except they add one object for drawing each time

so which one do i save? which one has most entropy in this case?
