### ISSUE TITLE
Error: Unable to start engine process (code: 3221225781)

### ISSUE THREAD

**Issue by Evinix** [CheshireCaat/puppeteer-with-fingerprints#88]
Hello, I runned:
- npm i puppeteer puppeteer-with-fingerprints
Then tried to run code from example, got this:

`C:\Users\Administrator\Desktop\GCvc0\node_modules\bas-remote-node\src\services\engine.js:114
          throw new Error(`Unable to start engine process (code: ${error.code})\n${INVALID_ENGINE_ERROR}`);
          ^

Error: Unable to start engine process (code: 3221225781)
This could be due to the fact that the engine was not downloaded or unpacked correctly.
Try completely deleting the engine folder and restarting the code until it completes.
If this does not help, open an issue with a detailed description of the problem.
    at C:\Users\Administrator\Desktop\GCvc0\node_modules\bas-remote-node\src\services\engine.js:114:17
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v20.11.0`

Anyone know how to solve ?

**Comment by CheshireCaat** [comment]
Please refer to:

https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/61
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/71
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/6

**Comment by Evinix** [comment]
Hello,
Thank you everything worked well !
I contact you again because out of nowhere I am having this problem:
Error: Error: ENOENT: no such file or directory, lstat
'C:\Users\Administrator\Desktop\gc\data\run\FingerprintPluginV6\b23a0\.lock'
Everything was working fine, then it started to happen, I tried to
reinstall puppeteer-with-fingerprints but it's still not work.

Le mar. 9 avr. 2024 à 06:42, CheshireCaat ***@***.***> a
écrit :
