### ISSUE TITLE
Browser Language Leak?

### ISSUE THREAD

**Issue by imnobody221** [CheshireCaat/puppeteer-with-fingerprints#92]
**Not sure this can be called leak or not or my lack of understanding.**

Browser Language not same as state in requested Fingerprint.

**Below is my example Script**

```
import { plugin } from 'puppeteer-with-fingerprints'

async function checkLang() {
	// Apply Fingerprint
	const fingerprint = await plugin.fetch(finger.Key, {
		tags: ['Microsoft Windows', 'Chrome'],
	})

	plugin.useFingerprint(fingerprint)

	const browser = await plugin.launch({
		headless: false,
	})

	const pages = await browser.pages()
	const page = await pages[0]

	//Check FingerLang
	const fingerprintLang = (await JSON.parse(fingerprint))['lang']

	//Check FingerLang in Browserleak
	await page.goto('https://browserleaks.com/ip', { waitUntil: 'networkidle0' })

	console.log('Fingerprint Lang: ' + fingerprintLang)
	console.log(
		'Accept-Language: ',
		await page.$eval('xpath/' + '//td[text()="Accept-Language"]/following-sibling::td', (el) => el.innerText)
	)

	await page.goto('https://browserleaks.com/javascript', { waitUntil: 'networkidle0' })
	console.log('navigator.language: ', await page.$eval('xpath/' + '//td[@id="js-language"]', (el) => el.innerText))
	console.log('navigator.languages: ', await page.$eval('xpath/' + '//td[@id="js-languages"]', (el) => el.innerText))
}

await checkLang()
```

**Output Log as below:** 
Output 1:
> Fingerprint Lang: ru,en;q=0.9,ru-RU;q=0.8
Accept-Language:  en,en;q=0.9,en-GB;q=0.8
navigator.language:  en
navigator.languages:  ["en","en-GB"]

Output 2:
> Fingerprint Lang: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6,uk;q=0.5
Accept-Language:  en-GB,en;q=0.9,en-US;q=0.8,en;q=0.7
navigator.language:  en-GB
navigator.languages:  ["en-GB","en","en-US"]

when using Proxy the browser language show as expected, but not without it.

Do we need extra step to change browser languages same as requested fingerprint['lang']? or this is expected outcome?

**Comment by bablosoft** [comment]
The case described in original post is not an issue. Fingerprint lang value is treated more like an template, it is mixed with proxy external ip to get final lang value.

> yes I can confirm the issue, just test it here https://mihneamanolache.github.io/simple-sw-test/ and you will see

Regarding this test, this could be an issue, we will review it soon, and if issue reproduces release patch asap.

**Comment by pgamaster** [comment]
Thank you and please release the latest version of Chrome (123.0.0.0 ) asap. These 2 things are actually stopping from buying a premium FP subscription. I see that BAS is updated but this puppeteer version is not. Thank you!

**Comment by pgamaster** [comment]
Also please check https://bot.sannysoft.com/ in iframe (create a dummy web page and put the url in iframe). you will see also the problem with languages....

**Comment by bablosoft** [comment]
> Also please check https://bot.sannysoft.com/ in iframe (create a dummy web page and put the url in iframe). you will see also the problem with languages....

I don't see any issue with this test, even if I put it in a frame.

Are you sure that there is an issue?

Could you provide more details, project and detailed description?

**Comment by pgamaster** [comment]
I'm trying to set a custom language, so I decided to alter the header, chrome args and navigator. I wouldn't need it if I could set the language just bu putting it in the fingerprint.

I belive we need an option to set a custom language array like: ["ru", "us", "us-US"]

here are pieces of my code that fixes most of the things but not in iframe...

const requestHeaders = {
        'Accept-Language': 'de,en-US;q=0.9',
    };

const options = {
        headless: false,
        args: [
            '--accept-lang=' + 'de,en-US',
            '--lang=' + 'de,en-US',
        ]
    };
 const browser = await plugin.launch(options);

const page = await browser.newPage();

await page.evaluateOnNewDocument(() => {
        Object.defineProperty(navigator, "language", {
            get: function() {
                return "de";
            }
        });
        Object.defineProperty(navigator, "languages", {
            get: function() {
                return ["de", "en-US"];
            }
        });
    });

    await page.setExtraHTTPHeaders({...requestHeaders}); 

  await page.goto('https://bot.sannysoft.com/'); //

await page.goto('https://bot.sannysoft.com/'); // run this in iframe

**Comment by bablosoft** [comment]
```javascript

await page.evaluateOnNewDocument(() => {
        Object.defineProperty(navigator, "language", {
            get: function() {
                return "de";
            }
        });
        Object.defineProperty(navigator, "languages", {
            get: function() {
                return ["de", "en-US"];
            }
        });
    });

```

Case is not valid, because this code can be easily detected.

**Comment by pgamaster** [comment]
I forgot to mention that I added '--disable-site-isolation-trials' flag. It works, most of the tests it passes. Anyway could you please allow us set custom languages?

**Comment by bablosoft** [comment]
Use proxy, it will change all properties automatically.

**Comment by pgamaster** [comment]
Well, the website I'm working with is using browser languages as a fingerprint, and I need to randomize it.

**Comment by pgamaster** [comment]
> Use proxy, it will change all properties automatically.

https://mihneamanolache.github.io/simple-sw-test/ will not pass then, the site I'm using detects fake browser by using a service worker

**Comment by bablosoft** [comment]
This issue is already fixed, wait for release.

**Comment by pgamaster** [comment]
> This issue is already fixed, wait for release.
hope in BAS it will be fixed too
