### ISSUE TITLE
Cannot Download & install FastExecuteScriptProtected.x64.zip

### ISSUE THREAD

**Issue by n3il9x** [CheshireCaat/puppeteer-with-fingerprints#93]
![2024-03-30 16 36 50](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/134495036/021f5685-839f-4832-a96d-be0019f6b30c)

**Comment by n3il9x** [comment]
version 1.4.7

**Comment by singhaditya4** [comment]
same

**Comment by singhaditya4** [comment]
<img width="662" alt="image" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/134913857/9f71fb54-4784-47bd-91fa-43fd7d883f29">
New engine update is the culprit

**Comment by CheshireCaat** [comment]
Please refer to:

https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/61
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/71
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/6
