### ISSUE TITLE
Any way to force a cetain browser engine version like 27.1.1 or 26.8.0 ?

### ISSUE THREAD

**Issue by singhaditya4** [CheshireCaat/puppeteer-with-fingerprints#95]
whenever an update happens it screws up the engine version and downloads the latest one but my Indian IP is throttled by your Server whenever i download i get super low speeds and have to use vpn to fix it , when i try multi threaded applications with same engine directory this causes a huge issue any way to set the engine  version ?

**Comment by singhaditya4** [comment]
<img width="662" alt="image" src="https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/134913857/45853413-9a8c-4dff-a528-41f5217baf63">
Entire Engine is screwed by the latest update, it auto updates itself and fucks up everything and there's no rolling back, how do i force it to use only version 26.8.0 which is my local latest version that works

**Comment by CheshireCaat** [comment]
@singhaditya4 Please stop spamming the same type of messages in several tickets. You cannot specify a specific version of the engine to work with - at the next update, I will additionally indicate the transition to a new one, so you can stay on the old one simply without updating the versions.

As for the error from the screenshot, the problem has already been described many times, also please refer to:

https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/61
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/71
https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/6
