### ISSUE TITLE
setting the viewport size is not allowed (limited by fingerprint).

### ISSUE THREAD

**Issue by MadhabaPatra** [CheshireCaat/puppeteer-with-fingerprints#96]
Hi @CheshireCaat  , 

I purchased the license. I'm getting this error while setting the viewport in headful mode. 
 
My problem statement is to set the browser full screen by 
`await page.setViewport({ width: 1255, height: 800, });`
or 
`args: ['--start-maximized']`

both are not working.

**Comment by bablosoft** [comment]
Viewport is changed when setting fingerprint. Changing it manually is not allowed.
