### ISSUE TITLE
Can't launch browser

### ISSUE THREAD

**Issue by hoaibao232** [CheshireCaat/puppeteer-with-fingerprints#97]
Today I have a problem. The browser can't launch, timeout problem.

**Comment by bablosoft** [comment]
Please atach more info

**Comment by hoaibao232** [comment]
![screenshot 2024-04-17 lúc 19 49 24](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/36413778/da32dbd0-4d6f-4f1c-9cbf-09ef130cd508)
Please check it

**Comment by bablosoft** [comment]
Please attach **minimal** source code and error string, not screenshot

**Comment by hoaibao232** [comment]
> C:\Users\Administrator\Documents\AUTO_SHOPEE\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:34
>             () => reject(new Error(`Timed out while calling the "${name}" method.`)),
>                          ^
> 
> Error: Timed out while calling the "setup" method.
>     at Timeout._onTimeout (C:\Users\Administrator\Documents\AUTO_SHOPEE\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:34:26)
>     at listOnTimeout (node:internal/timers:569:17)
>     at process.processTimers (node:internal/timers:512:7)

![screenshot 2024-04-17 lúc 19 54 01](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/36413778/c9d391e6-84c3-4b44-8947-0606bafc5c3f)

**Comment by bablosoft** [comment]
Please attach minimal source code

**Comment by hoaibao232** [comment]
My minimal source code

 
> plugin.useProxy(`${currentproxyAddresss}:${currentproxyPort}@${proxyUser}:${proxyPass}`, {
>     detectExternalIP: true,
>     changeGeolocation: true,
>     changeBrowserLanguage: true,
>     changeTimezone: true,
>     changeWebRTC: true,
> });
>   }
>    
>     const userAgent = new UserAgent({ platform: 'MacIntel', deviceCategory: 'desktop' });
>     const userAgentStr = userAgent.toString();
>     console.log(`User Agent: ${userAgentStr}`);
> 
>     const anonymizeUserAgentPlugin = require('puppeteer-extra-plugin-anonymize-ua')({
>         customFn: () => userAgentStr,
>         stripHeadless: true,
>         makeWindows: false,
>     });
>     puppeteer.use(anonymizeUserAgentPlugin);
> 	
>         plugin.launch({ headless: false,
>           args: ['--disable-notifications',
>           '--start-maximized',
>               ],
> 
>         userDataDir: './profile/gpt',
>         executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe"
> 
>         }).then(async browser => {
>       
>             const page = await browser.newPage();
>           })

**Comment by bablosoft** [comment]
not connected to puppeteer-with-fingerprints

**Comment by hoaibao232** [comment]
I had this code above

>   const puppeteer = require('puppeteer-extra')
>   
>   const fingerprint = await plugin.fetch('', {
>   tags: ['Microsoft Windows', 'Chrome'],
> });
> 			
> plugin.useFingerprint(fingerprint);

**Comment by hoaibao232** [comment]
> not connected to puppeteer-with-fingerprints

I had this code above. It's connected

> const puppeteer = require('puppeteer-extra')
> 
> const fingerprint = await plugin.fetch('', {
> tags: ['Microsoft Windows', 'Chrome'],
> });
> 
> plugin.useFingerprint(fingerprint);

**Comment by hoaibao232** [comment]
@bablosoft Hi, please help me
