### ISSUE TITLE
need help post

### ISSUE THREAD

**Issue by RealDevBd** [CheshireCaat/puppeteer-with-fingerprints#98]
hi sir, i am using your package and its jut mindblowing. i need a help sir. i am using puppeteer with your package. i do not want to create profile file inside data file. how to stop creating profile file?

**Comment by CheshireCaat** [comment]
You cannot disable the profile folders usage at all, but you can periodically clear the folder with profiles, or specify your own at startup and, if necessary, delete unnecessary ones or reuse them, for example:

```js
const fs = require('fs'); 
const { plugin } = require('puppeteer-with-fingerprints');

const browser = await plugin.launch({
  args: [`--user-data-dir=${__dirname}/profile`],
});
// your code
await browser.close();
// remove profile
await fs.promises.rmdir(`${__dirname}/profile`, { recursive: true });
```
