### ISSUE TITLE
Trojan detected on Windows Defender 

### ISSUE THREAD

**Issue by wiz64** [CheshireCaat/puppeteer-with-fingerprints#99]
The browser engine is being detected as a Trojan  win32/2nyonm

![IMG_20240429_094828.png](https://github.com/CheshireCaat/puppeteer-with-fingerprints/assets/67432394/157d957a-75c2-4437-bea3-85228c5ce66a)

Is bablo really trustable ? Or is it an actual Trojan inside ?

**Comment by bablosoft** [comment]
This is false positive because we are using protector.

**Comment by wiz64** [comment]
> This is false positive because we are using protector.

What do you mean by protector here ? Can you tell the name ?

**Comment by bablosoft** [comment]
> What do you mean by protector here ?

Software protectors were created to keep an attacker from directly inspecting or modifying a compiled application. A software protector is like a shield that keeps an application encrypted and protected against possible attacks.

> Can you tell the name ?

No
